telemetry/core.schema.json, telemetry/crash.schema.json, telemetry/main.schema.json, telemetry/vacuous.schema.json
This incorporates #10. These are the changes I have determined empirically cause the new infrastructure to most closely resemble the current infrastructure from a validation perspective.
@mreid-moz or @trink r?
=> Fix up schemas for first prod deploy

telemetry/main.schema.json, validation/telemetry/sample_v4_ping.json
This also adds the missing schema entry for
boolean scalars.
=> Add keyedScalars to the main ping schema

telemetry/main.schema.json, validation/telemetry/sample_v4_ping.json
=> bug 1288045 - update schema to account for changes from bug 1218576

shield-study/shield-study-addon.schema.json, shield-study/shield-study-error.schema.json, shield-study/shield-study.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/19)
=> Shield Study doc_type JSON Schemas

telemetry/shield-study-addon.schema.json, telemetry/shield-study-error.schema.json, telemetry/shield-study.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/21)
=> Schemas from gregglind/shield-study-schemas, updated

telemetry/shield-study-addon.schema.json, telemetry/shield-study-error.schema.json, telemetry/shield-study.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/22)
=> 0.6.1 iteration of the V3 spec.  'type' is required.

metadata/metadata_sources.schema.json
This doesn't do anything but I've added it for completeness.
@mreid-moz r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/25)
=> Add parquet to record_format

telemetry/core.schema.json
...or acknowledge that we want to discard these.
@mreid-moz r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/27)
=> Allow null for defaultSearch

validation/main-ping-validation-with-jsonschema.ipynb
This commit fixes the validation notebook, which was broken
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/28)
=> Make the validation notebook work again

telemetry/crash.schema.json, telemetry/main.schema.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/29)
=> Bug 1330897 - Update the schema for the main ping

telemetry/shield-study-addon.parquetmr.txt, telemetry/shield-study-addon.schema.json, telemetry/shield-study-error.parquetmr.txt, telemetry/shield-study-error.schema.json, telemetry/shield-study.parquetmr.txt, telemetry/shield-study.schema.json
- jsonschema 'number' => double
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/30)
=> shield-schemas-v3, 0.9.0 series

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/33)
=> Add some documentation links

telemetry/anonymous.schema.json, validation/telemetry/sample_anonymous_ping.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/38)
=> Bug 1329157 - Add anonymous ping. r?frank

telemetry/anonymous.parquetmr.txt
This is for direct-to-parquet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/40)
=> Add anonymous ping parquet schema

telemetry/core.parquetmr.txt, telemetry/core.schema.json
Also added the parquetmr format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/41)
=> Bug 1353784 - Update core schema with optional campaign field

telemetry/anonymous.parquetmr.txt, telemetry/anonymous.schema.json
@trink r?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/42)
=> Fix anonymous ping schema

schemas/telemetry/new-profile/new-profile.4.parquetmr.txt
=> Bugzilla 1360256 Add a new-profile ping parquet schema

schemas/telemetry/focus-event/focus-event.1.schema.json, templates/telemetry/focus-event/focus-event.1.parquetmr.txt, templates/telemetry/focus-event/focus-event.1.schema.json
=> Update focus-event template with schema changes

README.md
=> Include release details and instructions for contributing

validation/telemetry/focus-event.1.sample.json
=> Closes #57: Update focus-event to include "default browser" settings measurement

schemas/telemetry/update/update.4.schema.json, templates/telemetry/update/update.4.schema.json, validation/telemetry/update.4.sample.json
This is not to check in. For some reason, the `cmake ..` step fails with with the following error:
> CMake Error at CMakeLists.txt:48 (message):
>   invalid JSON telemetry/update/update.4.schema.json - No such file or
>   directory
> 
The "No such file or directory" part is there because I've printed the `JQ_RV` result variable in `CMakeLists.txt`.
=> Introduce the "update" ping schema

schemas/telemetry/health/health.4.parquetmr.txt, schemas/telemetry/health/health.4.schema.json, templates/telemetry/health/health.4.parquetmr.txt, templates/telemetry/health/health.4.schema.json, validation/telemetry/health.4.sample.json
[Bug 1383730](https://bugzilla.mozilla.org/show_bug.cgi?id=1383730) and [Bug 1381783](https://bugzilla.mozilla.org/show_bug.cgi?id=1381783).
[Health ping docs.](http://gecko.readthedocs.io/en/latest/toolkit/components/telemetry/telemetry/data/health-ping.html)
=> Add parquet and json schemas for Health ping

schemas/heka/telemetry/moz_ingest_uri_errors.1.parquetmr.txt, templates/heka/telemetry/moz_ingest_uri_errors.1.parquetmr.txt, tests/hindsight/run/input/test_heka_messages.lua
=> Bug 1400939 Add parquet output for URI errors

.travis.yml, Dockerfile, schemas/telemetry/update/update.4.parquetmr.txt, templates/telemetry/update/update.4.parquetmr.txt
Refs https://bugzilla.mozilla.org/show_bug.cgi?id=1405614
f? @mreid-moz
=> Add  displayVersion to the update_parquet schema

.travis.yml, Dockerfile
=> Running tests on travis with docker.

schemas/pioneer-study/event.1.parquetmr.txt, schemas/pioneer-study/event.1.schema.json, schemas/pioneer-study/online-news-log.1.parquetmr.txt, schemas/pioneer-study/online-news-log.1.schema.json, schemas/telemetry/pioneer-study/pioneer-study.4.schema.json, templates/pioneer-study/event.1.parquetmr.txt, templates/pioneer-study/event.1.schema.json, templates/pioneer-study/online-news-log.1.parquetmr.txt, templates/pioneer-study/online-news-log.1.schema.json, templates/telemetry/pioneer-study/pioneer-study.4.schema.json, tests/hindsight/run/input/test_json_schemas.lua, tests/hindsight/run/output/test_parquet_schemas.lua, validation/pioneer-study/event.1.schema.json, validation/pioneer-study/example.1.sample.json, validation/pioneer-study/online-news-log.1.sample.json, validation/telemetry/pioneer-study.4.sample.json
r? @rehandalal (cc: @mythmon @crankycoder)
replaces #94
=> Add the pioneer-study online-news schemas

schemas/telemetry/heartbeat/heartbeat.4.parquetmr.txt, schemas/telemetry/heartbeat/heartbeat.4.schema.json, templates/telemetry/heartbeat/heartbeat.4.parquetmr.txt, templates/telemetry/heartbeat/heartbeat.4.schema.json, validation/telemetry/heartbeat.4.sample.json
=> Bug 1401787 - Add heartbeat ping schema

schemas/pioneer-study/pathfinder-event.1.parquetmr.txt, schemas/pioneer-study/pathfinder-event.1.schema.json, schemas/pioneer-study/pathfinder-log.1.parquetmr.txt, schemas/pioneer-study/pathfinder-log.1.schema.json, templates/pioneer-study/pathfinder-event.1.parquetmr.txt, templates/pioneer-study/pathfinder-event.1.schema.json, templates/pioneer-study/pathfinder-log.1.parquetmr.txt, templates/pioneer-study/pathfinder-log.1.schema.json
The new schemas required for the pathfinder study we are building.
r?
/cc: @sunahsuh
=> Add schemas for pioneer pathfinder study

schemas/pioneer-study/esper-study-telemetry.1.parquetmr.txt, schemas/pioneer-study/esper-study-telemetry.1.schema.json
These never got checked into schemas/, only templates/.
=> Add missing esper study artifacts

Dockerfile
Removes the dependencies from the pinned parquet-cpp library and reformats the Dockefile.
=> Remove pinned parquet-cpp dependencies

schemas/pioneer-study/esper-study-telemetry.1.schema.json, schemas/pioneer-study/pathfinder-event.1.schema.json, schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/update/update.4.schema.json, templates/include/telemetry/environment.1.schema.json
[Bug 1431198](https://bugzilla.mozilla.org/show_bug.cgi?id=1431198)
This updates the environment schema to include the `environment/system/sec` field.
=> Bug 1431198 - Add security environment field

README.md
=> Update README on running tests via docker (#106)

schemas/telemetry/shield-study-icq/shield-study-icq.4.schema.json, templates/telemetry/shield-study-icq/shield-study-icq.4.schema.json, validation/telemetry/shield-study-icq.4.error.json, validation/telemetry/shield-study-icq.4.progress.json
Let's review but not merge: it's pending data-review!
=> Add the schema for the ICQ v1 SHIELD study

schemas/pioneer-study/pathfinder-event.1.schema.json, templates/pioneer-study/pathfinder-event.1.schema.json
=> Fix min length in pioneer pathfinder event schema

schemas/pioneer-study/online-news-log.2.parquetmr.txt, schemas/pioneer-study/online-news-log.2.schema.json, templates/pioneer-study/online-news-log.2.parquetmr.txt, templates/pioneer-study/online-news-log.2.schema.json
=> Add v2 of pioneer online news log schema

schemas/telemetry/crash/crash.4.schema.json, templates/telemetry/crash/crash.4.schema.json, validation/telemetry/crash.4.sample.pass.json
Add `metadata.StartupCrash` field, specify required fields.
=> Update crash ping schema

schemas/telemetry/core/core.2.schema.json, schemas/telemetry/core/core.3.schema.json, schemas/telemetry/core/core.4.schema.json, schemas/telemetry/core/core.5.schema.json, schemas/telemetry/core/core.6.schema.json, schemas/telemetry/core/core.7.schema.json, schemas/telemetry/core/core.8.schema.json, schemas/telemetry/core/core.9.schema.json, templates/include/telemetry/coreCommon.2.schema.json, validation/telemetry/core.9.displayversion.fail.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1461772
=> Add optional displayVersion field to core ping

schemas/telemetry/new-profile/new-profile.4.parquetmr.txt
#155 only updated the template, and not the compiled version
=> Update compiled new-profile parquet schema

schemas/telemetry/core/core.9.parquetmr.txt, templates/telemetry/core/core.9.parquetmr.txt
=> Bug 1473129 - Add appVersion field to core parquet.

schemas/telemetry/optout/optout.4.schema.json, templates/telemetry/optout/optout.4.schema.json, validation/telemetry/optout.4.clientid.fail.json, validation/telemetry/optout.4.payload.fail.json, validation/telemetry/optout.4.sample.pass.json
[Bug 1445921](https://bugzilla.mozilla.org/show_bug.cgi?id=1445921) implements the optout ping.
This provides the schema for it.
=> Bug 1445921 - Add schema for optout ping

schemas/heka/telemetry/moz_ingest_uri_errors.1.parquetmr.txt, schemas/heka/telemetry/telemetry_errors.1.parquetmr.txt, templates/heka/telemetry/moz_ingest_uri_errors.1.parquetmr.txt, templates/heka/telemetry/telemetry_errors.1.parquetmr.txt
Pursuant to https://github.com/mozilla-services/lua_sandbox_extensions/issues/310.
=> Add DecodeErrorDetail to heka datasets

schemas/coverage/coverage/coverage.1.parquetmr.txt, schemas/coverage/coverage/coverage.1.schema.json, templates/coverage/coverage/coverage.1.parquetmr.txt, templates/coverage/coverage/coverage.1.schema.json, validation/coverage/coverage.1.extra_field.fail.json, validation/coverage/coverage.1.missing_field.fail.json, validation/coverage/coverage.1.sample.pass.json
My editor adds newlines, but whatever. CI is failing, looking into that now.
=> Change coverage ping telemetryEnabled to integer type

schemas/glean/baseline/baseline.1.schema.json, templates/include/glean/glean.1.schema.json, validation/glean/baseline.1.all.pass.json
This adds a special metric type for handling UUIDs.
=> Add UUID metric type to glean schema

schemas/glean/baseline/baseline.1.schema.json, templates/include/glean/glean.1.schema.json, validation/glean/baseline.1.all.pass.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1497807
=> [glean] Add place to store information about active experiments

schemas/glean/baseline/baseline.1.schema.json, templates/include/glean/glean.1.schema.json, validation/glean/baseline.1.all.pass.json
Since experiments are always sent with every ping, they should be in the ping_info section.
=> 1510308: experiments should be in the ping_info section

schemas/glean/events/events.1.schema.json, templates/glean/events/events.1.schema.json, validation/glean/events.1.all.pass.json
Fixes [1510552](https://bugzilla.mozilla.org/show_bug.cgi?id=1510552).
=> Add glean events docType

schemas/pocket/fire-tv-events/fire-tv-events.1.parquetmr.txt, schemas/pocket/fire-tv-events/fire-tv-events.1.schema.json, templates/pocket/fire-tv-events/fire-tv-events.1.parquetmr.txt, templates/pocket/fire-tv-events/fire-tv-events.1.schema.json, tests/hindsight/run/input/test_json_schemas.lua, validation/pocket/fire-tv-events.1.sample.pass.json
=> Bug 1513590: Add Pocket Fire-TV Events Ping

schemas/telemetry/core/core.10.schema.json, templates/telemetry/core/core.10.schema.json, validation/telemetry/core.10.sample.pass.json
Version was increased as part of
https://hg.mozilla.org/mozilla-central/rev/5cb4e28e1eb8
=> Add schema for core ping version 10

schemas/glean/events/events.1.parquetmr.txt, schemas/org-mozilla-samples-glean/baseline/baseline.1.parquetmr.txt, schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json, schemas/org-mozilla-samples-glean/events/events.1.parquetmr.txt, schemas/org-mozilla-samples-glean/events/events.1.schema.json, templates/glean/events/events.1.parquetmr.txt, templates/org-mozilla-samples-glean/baseline/baseline.1.parquetmr.txt, templates/org-mozilla-samples-glean/baseline/baseline.1.schema.json, templates/org-mozilla-samples-glean/events/events.1.parquetmr.txt, templates/org-mozilla-samples-glean/events/events.1.schema.json, validation/org-mozilla-samples-glean/baseline.1.all.pass.json, validation/org-mozilla-samples-glean/baseline.1.core.pass.json, validation/org-mozilla-samples-glean/events.1.all.pass.json
This is needed since the namespace changed in the sample application itself. We don't care too much about loosing the data, as this is a sample application.
=> Rename the `glean` namespace to `org-mozilla-samples-glean`

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/untrustedModules/untrustedModules.4.schema.json, schemas/telemetry/update/update.4.schema.json, templates/include/telemetry/environment.1.schema.json, validation/telemetry/modules.4.linux.pass.json, validation/telemetry/modules.4.mac.pass.json, validation/telemetry/modules.4.windows.pass.json
I chose the modules ping to add null scopes to since that's the one that we're actually seeing ingestion errors with.
=> Issue 240 - allow null scope for addons

schemas/glean/baseline/baseline.1.schema.json, schemas/glean/events/events.1.schema.json, schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json, schemas/org-mozilla-reference-browser/events/events.1.schema.json, schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json, schemas/org-mozilla-samples-glean/events/events.1.schema.json, templates/include/glean/glean.1.schema.json, validation/glean/baseline.1.all.pass.json, validation/glean/baseline.1.core.pass.json, validation/glean/events.1.all.pass.json, validation/org-mozilla-samples-glean/baseline.1.all.pass.json, validation/org-mozilla-samples-glean/baseline.1.core.pass.json, validation/org-mozilla-samples-glean/events.1.all.pass.json
=> Add the "app_display_version" to the glean pings

schemas/glean/metrics/metrics.1.parquetmr.txt, schemas/glean/metrics/metrics.1.schema.json, schemas/org-mozilla-reference-browser/metrics/metrics.1.parquetmr.txt, schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json, schemas/org-mozilla-samples-glean/metrics/metrics.1.parquetmr.txt, schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json, templates/glean/metrics/metrics.1.parquetmr.txt, templates/glean/metrics/metrics.1.schema.json, templates/org-mozilla-reference-browser/metrics/metrics.1.parquetmr.txt, templates/org-mozilla-reference-browser/metrics/metrics.1.schema.json, templates/org-mozilla-samples-glean/metrics/metrics.1.parquetmr.txt, templates/org-mozilla-samples-glean/metrics/metrics.1.schema.json, validation/glean/metrics.1.all.pass.json, validation/org-mozilla-samples-glean/metrics.1.all.pass.json
Adding schema for glean metrics ping
=> Implement glean metrics ping

schemas/telemetry/heartbeat/heartbeat.4.parquetmr.txt, schemas/telemetry/heartbeat/heartbeat.4.schema.json, templates/telemetry/heartbeat/heartbeat.4.parquetmr.txt, templates/telemetry/heartbeat/heartbeat.4.schema.json, validation/telemetry/heartbeat.4.sample.pass.json
=> Add engagement type to heartbeat schema

templates/telemetry/crash/crash.4.schema.json
=> Fix indentation nit

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.parquetmr.txt, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/untrustedModules/untrustedModules.4.parquetmr.txt, schemas/telemetry/untrustedModules/untrustedModules.4.schema.json, schemas/telemetry/update/update.4.schema.json, templates/include/telemetry/environment.1.parquetmr.txt, templates/include/telemetry/environment.1.schema.json
=> Bug 1517639: Add launcherProcessState to telemetry environment schema

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/untrustedModules/untrustedModules.4.schema.json, schemas/telemetry/update/update.4.schema.json, templates/include/telemetry/environment.1.schema.json
=> Make environment an object

schemas/glean/baseline/baseline.1.parquetmr.txt, schemas/glean/baseline/baseline.1.schema.json, schemas/glean/events/events.1.parquetmr.txt, schemas/glean/events/events.1.schema.json, schemas/glean/metrics/metrics.1.parquetmr.txt, schemas/glean/metrics/metrics.1.schema.json, schemas/org-mozilla-reference-browser/baseline/baseline.1.parquetmr.txt, schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json, schemas/org-mozilla-reference-browser/events/events.1.parquetmr.txt, schemas/org-mozilla-reference-browser/events/events.1.schema.json, schemas/org-mozilla-reference-browser/metrics/metrics.1.parquetmr.txt, schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json, schemas/org-mozilla-samples-glean/baseline/baseline.1.parquetmr.txt, schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json, schemas/org-mozilla-samples-glean/events/events.1.parquetmr.txt, schemas/org-mozilla-samples-glean/events/events.1.schema.json, schemas/org-mozilla-samples-glean/metrics/metrics.1.parquetmr.txt, schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json, templates/include/glean/CHANGELOG.md, templates/include/glean/histogram.1.parquetmr.txt, templates/include/glean/histogram.1.schema.json, templates/include/glean/timing_distribution.1.schema.json, validation/glean/baseline.1.all.pass.json, validation/glean/metrics.1.all.pass.json
- [ x] Update `include/glean/CHANGELOG.md`
=> Add `sum` to glean histogram and timing_distribution schemas

schemas/glean/baseline/baseline.1.parquetmr.txt, schemas/glean/baseline/baseline.1.schema.json, schemas/glean/events/events.1.parquetmr.txt, schemas/glean/events/events.1.schema.json, schemas/glean/metrics/metrics.1.parquetmr.txt, schemas/glean/metrics/metrics.1.schema.json, schemas/org-mozilla-reference-browser/baseline/baseline.1.parquetmr.txt, schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json, schemas/org-mozilla-reference-browser/events/events.1.parquetmr.txt, schemas/org-mozilla-reference-browser/events/events.1.schema.json, schemas/org-mozilla-reference-browser/metrics/metrics.1.parquetmr.txt, schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json, schemas/org-mozilla-samples-glean/baseline/baseline.1.parquetmr.txt, schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json, schemas/org-mozilla-samples-glean/events/events.1.parquetmr.txt, schemas/org-mozilla-samples-glean/events/events.1.schema.json, schemas/org-mozilla-samples-glean/metrics/metrics.1.parquetmr.txt, schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json, templates/include/glean/glean.1.parquetmr.txt, templates/include/glean/glean.1.schema.json, validation/glean/metrics.1.all.pass.json
=> Add the "app_channel" to glean pings' `client_info`

schemas/glean/baseline/baseline.1.parquetmr.txt, schemas/glean/baseline/baseline.1.schema.json, schemas/glean/events/events.1.parquetmr.txt, schemas/glean/events/events.1.schema.json, schemas/glean/metrics/metrics.1.parquetmr.txt, schemas/glean/metrics/metrics.1.schema.json, schemas/org-mozilla-reference-browser/baseline/baseline.1.parquetmr.txt, schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json, schemas/org-mozilla-reference-browser/events/events.1.parquetmr.txt, schemas/org-mozilla-reference-browser/events/events.1.schema.json, schemas/org-mozilla-reference-browser/metrics/metrics.1.parquetmr.txt, schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json, schemas/org-mozilla-samples-glean/baseline/baseline.1.parquetmr.txt, schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json, schemas/org-mozilla-samples-glean/events/events.1.parquetmr.txt, schemas/org-mozilla-samples-glean/events/events.1.schema.json, schemas/org-mozilla-samples-glean/metrics/metrics.1.parquetmr.txt, schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json, templates/include/glean/event.1.schema.json, templates/include/glean/glean.1.parquetmr.txt, validation/glean/baseline.1.all.pass.json, validation/glean/events.1.all.pass.json, validation/glean/metrics.1.all.pass.json
=> Convert glean `event` schema from array to object

schemas/org-mozilla-fenix/baseline/baseline.1.parquetmr.txt, schemas/org-mozilla-fenix/baseline/baseline.1.schema.json, schemas/org-mozilla-fenix/events/events.1.parquetmr.txt, schemas/org-mozilla-fenix/events/events.1.schema.json, schemas/org-mozilla-fenix/metrics/metrics.1.parquetmr.txt, schemas/org-mozilla-fenix/metrics/metrics.1.schema.json, templates/org-mozilla-fenix/baseline/baseline.1.parquetmr.txt, templates/org-mozilla-fenix/baseline/baseline.1.schema.json, templates/org-mozilla-fenix/events/events.1.parquetmr.txt, templates/org-mozilla-fenix/events/events.1.schema.json, templates/org-mozilla-fenix/metrics/metrics.1.parquetmr.txt, templates/org-mozilla-fenix/metrics/metrics.1.schema.json
=> Add Fenix schemas :(

schemas/telemetry/pre-account/pre-account.4.parquetmr.txt, schemas/telemetry/pre-account/pre-account.4.schema.json, templates/telemetry/pre-account/pre-account.4.parquetmr.txt, templates/telemetry/pre-account/pre-account.4.schema.json, validation/telemetry/pre-account.4.sample.pass.json
=> Bug 1534730 - Schema for the pre-account ecosystem ping

schemas/org-mozilla-fenix/activation/activation.1.parquetmr.txt, schemas/org-mozilla-fenix/activation/activation.1.schema.json, templates/org-mozilla-fenix/activation/activation.1.parquetmr.txt, templates/org-mozilla-fenix/activation/activation.1.schema.json, validation/org-mozilla-fenix/activation.1.all.pass.json
=> Add schema for the Fenix activation ping

schemas/activity-stream/spoc-fills/spoc-fills.1.schema.json, templates/activity-stream/spoc-fills/spoc-fills.1.schema.json, validation/activity-stream/spoc-fills.1.sample.pass.json
=> Rename spocs-fills to spoc-fills for Activity Stream

schemas/mobile/activation/activation.1.schema.json, templates/mobile/activation/activation.1.schema.json, validation/mobile/activation.1.both_ids.fail.json, validation/mobile/activation.1.sample.pass.json
As described in the [Fennece Mobile Activation Ping design doc](https://docs.google.com/document/d/1D-0m3TRvIAOzGtkBNjaddyVr7baE7uEhiBUFyVQr2pg).
=> Add mobile/activation ping

schemas/firefox-installer/install/install.1.schema.json, templates/firefox-installer/install/install.1.schema.json
=> Add stub ping specific fields

schemas/telemetry/pre-account/pre-account.4.parquetmr.txt, templates/telemetry/pre-account/pre-account.4.parquetmr.txt, validation/telemetry/pre-account.4.with-null.pass.json
=> Consider speed as optional in parquet output

schemas/glean/baseline/baseline.1.schema.json, schemas/glean/events/events.1.schema.json, schemas/glean/metrics/metrics.1.schema.json, schemas/org-mozilla-fenix/activation/activation.1.schema.json, schemas/org-mozilla-fenix/baseline/baseline.1.schema.json, schemas/org-mozilla-fenix/events/events.1.schema.json, schemas/org-mozilla-fenix/metrics/metrics.1.schema.json, schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json, schemas/org-mozilla-reference-browser/events/events.1.schema.json, schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json, schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json, schemas/org-mozilla-samples-glean/events/events.1.schema.json, schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json, schemas/org-mozilla-tv-firefox/baseline/baseline.1.schema.json, schemas/org-mozilla-tv-firefox/events/events.1.schema.json, schemas/org-mozilla-tv-firefox/metrics/metrics.1.schema.json, templates/include/glean/CHANGELOG.md, templates/include/glean/labeled_group.1.schema.json
=> 1556684: Fix label length so it can support any metric name

schemas/glean/baseline/baseline.1.schema.json, schemas/glean/events/events.1.schema.json, schemas/glean/metrics/metrics.1.schema.json, schemas/org-mozilla-fenix/activation/activation.1.schema.json, schemas/org-mozilla-fenix/baseline/baseline.1.schema.json, schemas/org-mozilla-fenix/events/events.1.schema.json, schemas/org-mozilla-fenix/metrics/metrics.1.schema.json, schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json, schemas/org-mozilla-reference-browser/events/events.1.schema.json, schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json, schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json, schemas/org-mozilla-samples-glean/events/events.1.schema.json, schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json, schemas/org-mozilla-tv-firefox/baseline/baseline.1.schema.json, schemas/org-mozilla-tv-firefox/events/events.1.schema.json, schemas/org-mozilla-tv-firefox/metrics/metrics.1.schema.json, templates/include/glean/histogram.1.schema.json, templates/include/glean/time_unit.1.schema.json, templates/include/glean/timing_distribution.1.schema.json
Similar to #343 but for glean. Should be a no-op from a validation / structure standpoint. See [this gist](https://gist.github.com/acmiyaguchi/bbfb78590f0c5030c87ade879405d73e) for context.
=> Add missing string types for some enum fields.

schemas/org-mozilla-fenix/bookmarks_sync/bookmarks_sync.1.schema.json, schemas/org-mozilla-fenix/history_sync/history_sync.1.schema.json
This updates the rendered schemas per the template changes in #344.
I should've rebased and updated before merging that one.
=> Update fenix sync pings per #344

schemas/telemetry/main/main.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, templates/include/telemetry/gcItem.1.schema.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1555101
=> Increase number of phases in GC telemetry

schemas/glean/baseline/baseline.1.schema.json, schemas/glean/events/events.1.schema.json, schemas/glean/metrics/metrics.1.schema.json, schemas/org-mozilla-fenix/activation/activation.1.schema.json, schemas/org-mozilla-fenix/baseline/baseline.1.schema.json, schemas/org-mozilla-fenix/bookmarks_sync/bookmarks_sync.1.schema.json, schemas/org-mozilla-fenix/events/events.1.schema.json, schemas/org-mozilla-fenix/history_sync/history_sync.1.schema.json, schemas/org-mozilla-fenix/metrics/metrics.1.schema.json, schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json, schemas/org-mozilla-reference-browser/events/events.1.schema.json, schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json, schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json, schemas/org-mozilla-samples-glean/events/events.1.schema.json, schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json, schemas/org-mozilla-tv-firefox/baseline/baseline.1.schema.json, schemas/org-mozilla-tv-firefox/events/events.1.schema.json, schemas/org-mozilla-tv-firefox/metrics/metrics.1.schema.json, templates/include/glean/use_counter.1.schema.json, validation/glean/metrics.1.invalid_use_counter.fail.json
Again similar to #343 to fix transpiler-incompatible changes.
=> Fix incompatible types in glean schemas

.circleci/config.yml
=> Run integration tests against master

schemas/telemetry/main/main.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, templates/include/telemetry/mainPayload.1.schema.json
=> Add payload.info.sessionLength to main schema

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/untrustedModules/untrustedModules.4.schema.json, schemas/telemetry/update/update.4.schema.json, templates/include/telemetry/environment.1.schema.json
=> Add environment.settings.e10sMultiProcesses to common ping format

schemas/metadata/decoded/decoded.1.schema.json, schemas/metadata/error/error.1.schema.json, schemas/metadata/raw/raw.1.schema.json, templates/include/metadata/raw.1.schema.json, templates/include/metadata/telemetryIngestion.1.schema.json, templates/metadata/decoded/decoded.1.schema.json, templates/metadata/error/error.1.schema.json, templates/metadata/raw/raw.1.schema.json
=> Add schemas for non-lossy BQ sink

schemas/metadata/raw/raw.1.schema.json, templates/include/metadata/raw.1.schema.json
=> Remove error fields from raw schema

schemas/metadata/error/error.1.schema.json, templates/metadata/error/error.1.schema.json
Addresses https://github.com/mozilla/gcp-ingestion/issues/756
=> Add pipeline information to metadata/error

schemas/telemetry/new-profile/new-profile.4.schema.json, templates/telemetry/new-profile/new-profile.4.schema.json, validation/telemetry/new-profile.4.sample.pass.json
This is effectively the same as #371 but targets the "master" branch (that one accidentally targetted `dev`). Note that there's a terrible hack here to exclude the `processes` chunk from the BigQuery schema for now.
=> Add new profile scalars

README.md
=> Remove instructions to submit PRs against `dev`

README.md
=> Change reference to `dev` branch to `master`

schemas/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.parquetmr.txt, schemas/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.schema.json, templates/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.parquetmr.txt, templates/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.schema.json, validation/firefox-launcher-process/launcher-process-failure.1.sample.pass.json
This got merged into the wrong branch (dev).
=> Add is_admin_without_uac to the launcher-process-failure ping

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/untrustedModules/untrustedModules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json, validation/telemetry/main.4.privatesearchengine.fail.json, validation/telemetry/main.4.privatesearchenginedataloadpath.fail.json, validation/telemetry/main.4.privatesearchenginedataname.fail.json, validation/telemetry/main.4.privatesearchenginedataorigin.fail.json, validation/telemetry/main.4.privatesearchenginedataurl.fail.json, validation/telemetry/main.4.sample.pass.json
=> 1563016: Add private default search engine to environment schema

schemas/eng-workflow/build/build.1.schema.json, schemas/metadata/decoded/decoded.1.schema.json, templates/eng-workflow/build/build.1.schema.json, templates/metadata/decoded/decoded.1.schema.json
=> Require all client ids be uuids

schemas/telemetry/third-party-modules/third-party-modules.1.schema.json
=> Update third-party-modules for change in environment template

schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, templates/telemetry/third-party-modules/third-party-modules.4.schema.json, validation/telemetry/third-party-modules.4.minimal.pass.json, validation/telemetry/third-party-modules.4.moduleindex.fail.json, validation/telemetry/third-party-modules.4.sample.pass.json, validation/telemetry/third-party-modules.4.stackframe.fail.json, validation/telemetry/third-party-modules.4.trustflags.fail.json, validation/telemetry/third-party-modules.4.unknownmodule.pass.json
=> Fix the third-party-modules schema to use version 4

schemas/glean/baseline/baseline.1.schema.json, schemas/glean/events/events.1.schema.json, schemas/glean/metrics/metrics.1.schema.json, schemas/org-mozilla-fenix/activation/activation.1.schema.json, schemas/org-mozilla-fenix/baseline/baseline.1.schema.json, schemas/org-mozilla-fenix/bookmarks_sync/bookmarks_sync.1.schema.json, schemas/org-mozilla-fenix/events/events.1.schema.json, schemas/org-mozilla-fenix/history_sync/history_sync.1.schema.json, schemas/org-mozilla-fenix/metrics/metrics.1.schema.json, schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json, schemas/org-mozilla-reference-browser/events/events.1.schema.json, schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json, schemas/org-mozilla-tv-firefox/baseline/baseline.1.schema.json, schemas/org-mozilla-tv-firefox/events/events.1.schema.json, schemas/org-mozilla-tv-firefox/metrics/metrics.1.schema.json, templates/include/glean/CHANGELOG.md, templates/include/glean/glean.1.schema.json
=> 1582270: Increase experiment name length to match Kinto

schemas/telemetry/core/core.10.schema.json, schemas/telemetry/core/core.2.schema.json, schemas/telemetry/core/core.3.schema.json, schemas/telemetry/core/core.4.schema.json, schemas/telemetry/core/core.5.schema.json, schemas/telemetry/core/core.6.schema.json, schemas/telemetry/core/core.7.schema.json, schemas/telemetry/core/core.8.schema.json, schemas/telemetry/core/core.9.schema.json, templates/include/telemetry/coreCommon.2.schema.json, validation/telemetry/core.10.fennec.pass.json
=> Bug 1584194: Add new fennec fields

schemas/glean/baseline/baseline.1.schema.json, schemas/glean/events/events.1.schema.json, schemas/glean/metrics/metrics.1.schema.json, schemas/org-mozilla-fenix/activation/activation.1.schema.json, schemas/org-mozilla-fenix/baseline/baseline.1.schema.json, schemas/org-mozilla-fenix/bookmarks_sync/bookmarks_sync.1.schema.json, schemas/org-mozilla-fenix/events/events.1.schema.json, schemas/org-mozilla-fenix/history_sync/history_sync.1.schema.json, schemas/org-mozilla-fenix/metrics/metrics.1.schema.json, schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json, schemas/org-mozilla-reference-browser/events/events.1.schema.json, schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json, schemas/org-mozilla-tv-firefox/baseline/baseline.1.schema.json, schemas/org-mozilla-tv-firefox/events/events.1.schema.json, schemas/org-mozilla-tv-firefox/metrics/metrics.1.schema.json, templates/include/glean/CHANGELOG.md, templates/include/glean/labeled_group.1.schema.json
=> 1585017: Don't do regex validation on label names -- it's not necessary

schemas/activity-stream/impression-stats/impression-stats.1.schema.json, schemas/activity-stream/spoc-fills/spoc-fills.1.schema.json, schemas/messaging-system/cfr/cfr.1.schema.json, schemas/messaging-system/undesired-events/undesired-events.1.schema.json, templates/activity-stream/impression-stats/impression-stats.1.schema.json, templates/activity-stream/spoc-fills/spoc-fills.1.schema.json, templates/messaging-system/cfr/cfr.1.schema.json, templates/messaging-system/undesired-events/undesired-events.1.schema.json, validation/messaging-system/onboarding.1.event.pass.json, validation/messaging-system/undesired-events.1.event.pass.json
=> Add undesired events for messaging system

schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, templates/include/telemetry/mainPayload.1.schema.json
Doesn't look like I can actually add this to Mark's PR since it's from a personal fork. Fingers crossed we avoid merge conflicts!
=> Add all allowed process types to main ping

schemas/telemetry/sync/sync.5.schema.json, templates/telemetry/sync/sync.5.schema.json, validation/telemetry/sync.5.sample.pass.json
=> Add a top-level "os" struct.

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/untrustedModules/untrustedModules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json
=> Allow null for environment/system/os/installYear

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/untrustedModules/untrustedModules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json, validation/telemetry/main.4.services.pass.json
=> Update the environment bundle to include the services object. Fixes #442

schemas/telemetry/deletion-request/deletion-request.4.schema.json, templates/telemetry/deletion-request/deletion-request.4.schema.json, validation/telemetry/deletion-request.4.noclientid.fail.json, validation/telemetry/deletion-request.4.payload.fail.json, validation/telemetry/deletion-request.4.sample.pass.json
=> bug 1585410 - Implement deletion-request ping

schemas/activity-stream/spoc-fills/spoc-fills.1.schema.json, templates/activity-stream/spoc-fills/spoc-fills.1.schema.json, validation/activity-stream/spoc-fills.1.sample.pass.json
=> Add a new reason to activity-stream/spoc-fills

schemas/activity-stream/events/events.1.schema.json, templates/activity-stream/events/events.1.schema.json, validation/activity-stream/events.1.sample.pass.json
This ports `Tiles.assa_events_daily` to here.
@jklukas r?
=> Add events to Activity-Stream

.github/auto_assign.yml
https://github.com/kentaro-m/auto-assign
Put everyone on data platform
=> Add auto-assign bot

schemas/telemetry/core/core.10.schema.json, schemas/telemetry/core/core.2.schema.json, schemas/telemetry/core/core.3.schema.json, schemas/telemetry/core/core.4.schema.json, schemas/telemetry/core/core.5.schema.json, schemas/telemetry/core/core.6.schema.json, schemas/telemetry/core/core.7.schema.json, schemas/telemetry/core/core.8.schema.json, schemas/telemetry/core/core.9.schema.json, templates/include/telemetry/coreCommon.2.schema.json
=> Bug 1583525 - Add fennec PWAs to core ping

.gitignore, schemas/telemetry/crash/crash.4.schema.json, templates/telemetry/crash/crash.4.schema.json, validation/telemetry/crash.4.null_minidumphashsha256.pass.json
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1606523)
=> Bug 1606523 - Allow for null value in minidumpSha256Hash 

schemas/telemetry/sync/sync.4.schema.json, schemas/telemetry/sync/sync.5.schema.json, templates/include/telemetry/syncPayload.1.schema.json, validation/telemetry/sync.4.sample.pass.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1582317
Closes https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/471
=> Add syncNodeType to sync ping schema

.gitignore
This reverts commit 2ff37bb740dc9218676857f6fa96eac2cd79cc47 and fixes https://github.com/mozilla/mozilla-schema-generator/issues/87.
=> Revert "Add build/ folder to gitignore"

schemas/glean/glean/glean.1.schema.json, templates/include/glean/CHANGELOG.md, templates/include/glean/glean.1.schema.json
=> Make glean ping_type kebab

schemas/activity-stream/impression-stats/impression-stats.1.schema.json, templates/activity-stream/impression-stats/impression-stats.1.schema.json, validation/activity-stream/impression-stats.1.as-cn.pass.json
=> Add page for china build to activity stream impression_stats

schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, templates/include/telemetry/mainSchemaId.1.schema.json
=> Make the $id for main ping schema show version as "4"

schemas/activity-stream/events/events.1.schema.json, templates/activity-stream/events/events.1.schema.json, validation/activity-stream/events.1.as-cn.pass.json
Per @l-hedgehog, the custom build also covers this ping.
@jklukas r?
=> Add page for china build to activity stream events

schemas/telemetry/sync/sync.4.schema.json, schemas/telemetry/sync/sync.5.schema.json, templates/include/telemetry/syncPayload.1.schema.json, validation/telemetry/sync.4.nested_devices.pass.json, validation/telemetry/sync.4.sample.pass.json
=> Move devices directly under payload in sync pings

schemas/glean/glean/glean.1.schema.json, templates/include/glean/CHANGELOG.md, templates/include/glean/glean.1.schema.json, validation/glean/glean.1.locale.pass.json
=> Bug 1601489 - Add locale to client_info section

schemas/telemetry/sync/sync.4.schema.json, schemas/telemetry/sync/sync.5.schema.json, templates/include/telemetry/syncPayload.1.schema.json, validation/telemetry/sync.4.sample.pass.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1610907
=> Bug 1610907 Add missing sync ping devices fields

schemas/glean/glean/glean.1.schema.json, templates/include/glean/CHANGELOG.md, templates/include/glean/glean.1.schema.json, validation/glean/glean.1.baseline.pass.json
=> 1612940: Allow "null" extras in experiment

schemas/telemetry/deletion-request/deletion-request.4.schema.json, templates/telemetry/deletion-request/deletion-request.4.schema.json, validation/telemetry/deletion-request.4.payload.pass.json
=> bug 1604312 - Scalars can now appear in 'deletion-request' pings.

GRAVEYARD.md
This graveyard document is based on various other graveyard docs, like https://github.com/mozilla/gcp-ingestion/blob/master/GRAVEYARD.md.
=> Add a GRAVEYARD.md document

schemas/telemetry/core/core.10.schema.json, schemas/telemetry/core/core.2.schema.json, schemas/telemetry/core/core.3.schema.json, schemas/telemetry/core/core.4.schema.json, schemas/telemetry/core/core.5.schema.json, schemas/telemetry/core/core.6.schema.json, schemas/telemetry/core/core.7.schema.json, schemas/telemetry/core/core.8.schema.json, schemas/telemetry/core/core.9.schema.json, templates/include/telemetry/coreCommon.2.schema.json, templates/telemetry/core/core.10.schema.json, validation/telemetry/core.10.enhancedSearch.pass.json
[buglink](https://bugzilla.mozilla.org/show_bug.cgi?id=1612935)
https://sql.telemetry.mozilla.org/queries/68956/source
https://sql.telemetry.mozilla.org/queries/68955/source
=> Bug 1612935 - Missing enhancedSearch fields in telemetry.core_v10 pings

schemas/activity-stream/events/events.1.schema.json, schemas/activity-stream/impression-stats/impression-stats.1.schema.json, schemas/activity-stream/sessions/sessions.1.schema.json, schemas/activity-stream/spoc-fills/spoc-fills.1.schema.json, schemas/messaging-system/cfr/cfr.1.schema.json, schemas/messaging-system/onboarding/onboarding.1.schema.json, schemas/messaging-system/snippets/snippets.1.schema.json, schemas/messaging-system/undesired-events/undesired-events.1.schema.json, templates/activity-stream/events/events.1.schema.json, templates/activity-stream/impression-stats/impression-stats.1.schema.json, templates/activity-stream/sessions/sessions.1.schema.json, templates/activity-stream/spoc-fills/spoc-fills.1.schema.json, templates/include/activity-stream/experiments.1.schema.json, templates/messaging-system/cfr/cfr.1.schema.json, templates/messaging-system/onboarding/onboarding.1.schema.json, templates/messaging-system/snippets/snippets.1.schema.json, templates/messaging-system/undesired-events/undesired-events.1.schema.json, validation/activity-stream/events.1.experiments.pass.json, validation/activity-stream/impression-stats.1.experiments.pass.json, validation/activity-stream/sessions.1.sample.pass.json, validation/activity-stream/spoc-fills.1.sample.pass.json, validation/messaging-system/cfr.1.experiments.pass.json, validation/messaging-system/onboarding.1.experiments.pass.json, validation/messaging-system/undesired-events.1.event.pass.json
=> Bug 1623439 Replace shield_id with experiments for activity-stream etc

README.md
=> More syntax highlighting in readme

schemas/telemetry/heartbeat/heartbeat.4.schema.json, templates/telemetry/heartbeat/heartbeat.4.schema.json, validation/telemetry/heartbeat.4.sample.fail.json
=> Bug 1629641 - Add environment to heartbeat ping

schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, templates/include/telemetry/mainPayload.1.schema.json, validation/telemetry/main.4.slow_sql.fail.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1592263
This PR provides a schema for `slowSQL`. The BQ schema looks like in main.4.bq:
```
...
{
"description": "Slow SQL queries for both the main and other threads. The execution of an SQL statement is considered slow if it takes 50ms or more on the main thread or 100ms or more on other threads. Slow SQL statements will be automatically trimmed to 1000 characters.",
"fields": [
{
"fields": [
{
"mode": "REQUIRED",
"name": "key",
"type": "STRING"
},
{
"mode": "REPEATED",
"name": "value",
"type": "INT64"
}
],
"mode": "REPEATED",
"name": "main_thread",
"type": "RECORD"
},
{
"fields": [
{
"mode": "REQUIRED",
"name": "key",
"type": "STRING"
},
{
"mode": "REPEATED",
"name": "value",
"type": "INT64"
}
],
"mode": "REPEATED",
"name": …
```
=> [Bug 1592263] Provide schema for SlowSQL

schemas/metadata/pioneer-ingestion/pioneer-ingestion.1.schema.json, templates/metadata/pioneer-ingestion/pioneer-ingestion.1.schema.json, validation/metadata/pioneer-ingestion.1.sample.pass.json
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1636317)
=> Bug 1636317 - Add metadata schema for Pioneer ingestion

schemas/default-browser-agent/default-browser/default-browser.1.schema.json, templates/default-browser-agent/default-browser/default-browser.1.schema.json, validation/default-browser-agent/default-browser.1.sample_all_fields.pass.json
[Bug 1621703](https://bugzilla.mozilla.org/show_bug.cgi?id=1621703)
=> Bug 1621703 - Add default browser notification telemetry

schemas/telemetry/core/core.10.schema.json, schemas/telemetry/core/core.2.schema.json, schemas/telemetry/core/core.3.schema.json, schemas/telemetry/core/core.4.schema.json, schemas/telemetry/core/core.5.schema.json, schemas/telemetry/core/core.6.schema.json, schemas/telemetry/core/core.7.schema.json, schemas/telemetry/core/core.8.schema.json, schemas/telemetry/core/core.9.schema.json, templates/include/telemetry/coreCommon.2.schema.json, validation/telemetry/core.10.sample.pass.json
=> Bug 1640700 - Add "landings" field to the core ping.

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/untrustedModules/untrustedModules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json, validation/telemetry/third-party-modules.4.sample.pass.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1642396
=> [Bug 1642396] Add system.gfx.features.hwCompositing field to environment

schemas/telemetry/sync/sync.4.schema.json, schemas/telemetry/sync/sync.5.schema.json, templates/include/telemetry/syncMigration.1.schema.json
=> Make sync migration comprehensible for bigquery.

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/untrustedModules/untrustedModules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1652834
=> Bug 1652834 - Add gfx.EmbeddedInFirefoxReality field to environment.

validation/telemetry/xfocsp-error-report.4.sample.pass.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1654558#c11
=> Remove client id from xfocsp sample ping

schemas/telemetry/sync/sync.4.schema.json, schemas/telemetry/sync/sync.5.schema.json, templates/include/telemetry/syncItem.1.schema.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1642393
=> [Bug 1642393] Add restarted, uid and deviceID columns to sync items

validation/glean/glean.1.baseline.pass.json
Follow-on from https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/584
cc @brizental 
=> Add glean jwe example to baseline validation document

schemas/telemetry/account-ecosystem/account-ecosystem.4.schema.json, templates/include/telemetry/environmentAccountEcosystem.1.schema.json, templates/telemetry/account-ecosystem/account-ecosystem.4.schema.json, templates/telemetry/pre-account/pre-account.4.schema.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1635659#c16
=> Bug 1659514 Add reduced environment to telemetry/account-ecosystem

schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, templates/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, validation/telemetry/dnssec-study-v1.4.dnsresponses.pass.json
=> Bug 1660121 - Add separate data for A record queries with DNSSEC OK bit set

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/untrustedModules/untrustedModules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json, validation/telemetry/main.4.adapter_null_gpuactive.pass.json
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1657142)
=> Bug 1657142 - Add nullable GPUActive field for #/environment/system/gfx/adapters

schemas/telemetry/core/core.10.schema.json, schemas/telemetry/core/core.2.schema.json, schemas/telemetry/core/core.3.schema.json, schemas/telemetry/core/core.4.schema.json, schemas/telemetry/core/core.5.schema.json, schemas/telemetry/core/core.6.schema.json, schemas/telemetry/core/core.7.schema.json, schemas/telemetry/core/core.8.schema.json, schemas/telemetry/core/core.9.schema.json, templates/include/telemetry/coreCommon.2.schema.json
=> Bug 1637340 - openTabCount in core ping

schemas/telemetry/account-ecosystem/account-ecosystem.4.schema.json, templates/telemetry/account-ecosystem/account-ecosystem.4.schema.json
This omission is causing m-s-g to fail currently.
=> Add missing "type" to account-ecosystem schema

schemas/telemetry/account-ecosystem/account-ecosystem.4.schema.json, templates/telemetry/account-ecosystem/account-ecosystem.4.schema.json
Follow-up to #601 
It's been difficult to verify this locally with m-s-g, as I've gotten tripped up with local probe cache, etc. I am fairly certain this version now works cleanly with m-s-g.
The metaschema can't really help us test for things like these, as it only covers mozPipelineMetadata. We really aren't guaranteed anything about the structure of schema payloads. If there's a JSONSchema for determining whether a document is valid JSONSchema, though, that might be useful to prevent this.
=> Another missing type

schemas/firefox-accounts/account-ecosystem/account-ecosystem.1.schema.json, templates/firefox-accounts/account-ecosystem/account-ecosystem.1.schema.json, validation/firefox-accounts/account-ecosystem.1.sample.pass.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1663720
=> Bug 1663720 Add event and geo to account-ecosystem ping

schemas/telemetry/saved-session/saved-session.4.schema.json, templates/telemetry/saved-session/saved-session.4.schema.json
Reverts mozilla-services/mozilla-pipeline-schemas#605
=> Revert "[Bug 1656910] Remove saved-session schemas"

schemas/pioneer-debug/pioneer-enrollment/pioneer-enrollment.1.schema.json, schemas/pioneer-meta/pioneer-enrollment/pioneer-enrollment.1.schema.json, templates/include/pioneer-study/deletion-request.1.schema.json, templates/include/pioneer-study/pioneer-enrollment.1.schema.json, templates/pioneer-debug/deletion-request/deletion-request.1.schema.json, templates/pioneer-debug/pioneer-enrollment/pioneer-enrollment.1.schema.json, templates/pioneer-meta/defaults.schema.json, templates/pioneer-meta/pioneer-enrollment/pioneer-enrollment.1.schema.json, tests/test_validation_java.py, validation/telemetry/pioneer-study.4.enrollment-request.pass.json
[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1663857)
=> Bug 1663857 - Add pioneer-enrollment schemas to debug and meta

schemas/metadata/metaschema/metaschema.1.schema.json, templates/metadata/metaschema/metaschema.1.schema.json
The pipeline relies on this metadata as of https://github.com/mozilla/gcp-ingestion/pull/1374
=> Mark jwe_mappings metadata as implemented

scripts/extract_crash_annotation_fields
* switch to argparse because it gives better help and error messages
* add print lines so it tells you what it's doing as it goes along
* reformat with black
* add a note about how to run this
=> Yak shave extract_crash_annotation_fields for easier usage

schemas/metadata/metaschema/metaschema.1.schema.json, schemas/telemetry/xfocsp-error-report/xfocsp-error-report.4.schema.json, templates/metadata/metaschema/metaschema.1.schema.json, templates/telemetry/xfocsp-error-report/xfocsp-error-report.4.schema.json
Resolves https://github.com/mozilla/mozilla-schema-generator/pull/155#discussion_r501368859
=> Note special handling of xfocsp-error-report

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json
=> Bug 1669208 - Add fissionEnabled field to environment

schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/uninstall/uninstall.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json, validation/telemetry/third-party-modules.4.sample.pass.json, validation/telemetry/uninstall.4.sample.pass.json
This corresponds to telemetry added in https://bugzilla.mozilla.org/show_bug.cgi?id=1674866
=> Bug 1674866: Add 'wrSoftware' to schema

schemas/activity-stream/on-save-recs/on-save-recs.1.schema.json, schemas/activity-stream/pocket-button/pocket-button.1.schema.json, schemas/messaging-system/onboarding/onboarding.1.schema.json, templates/messaging-system/onboarding/onboarding.1.schema.json, validation/messaging-system/onboarding.1.attribution.pass.json
The schema change is located in [messaging-system/onboarding](https://github.com/mozilla-services/mozilla-pipeline-schemas/compare/master...ncloudioj:bz-1676437?expand=1#diff-de3dad70fe452fa74db75beb9be92195ffb3460d77f1ea597e9b426656ccb3c7). It also includes some unrelated changes in `on-save-recs` and `pocket-button` perhaps generated by the make script. Please let me know if we want to exclude those.
@jklukas r?
=> Bug 1676437 - Collect attribution data for Onboarding

schemas/telemetry/bhr/bhr.4.schema.json, schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/uninstall/uninstall.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json, validation/telemetry/third-party-modules.4.sample.pass.json, validation/telemetry/uninstall.4.sample.pass.json
=>  Bug 1687345 - Add "omtp" property to schemas

schemas/telemetry/crash/crash.4.schema.json, templates/telemetry/crash/crash.4.schema.json
=> Bug 1693116 - Quota Manager Shutdown Timeout annotation

Dockerfile
=> Bump jsonschema-transpiler to 1.9.0

schemas/telemetry/crash/crash.4.schema.json, templates/telemetry/crash/crash.4.schema.json
=> Bug 1586236 - Replace the annotation field in the crash ping

.circleci/config.yml, README.md, mozilla_pipeline_schemas/cli/bigquery.py, pom.xml, schemas/activity-stream/events/events.1.schema.json, schemas/messaging-system/infobar/infobar.1.schema.json, schemas/messaging-system/onboarding/onboarding.1.schema.json, schemas/messaging-system/whats-new-panel/whats-new-panel.1.schema.json, scripts/extract_probe_dictionary_descriptions, templates/activity-stream/events/events.1.schema.json, templates/messaging-system/infobar/infobar.1.schema.json, templates/messaging-system/onboarding/onboarding.1.schema.json, templates/messaging-system/whats-new-panel/whats-new-panel.1.schema.json, tests/conftest.py, tests/test_mps_bigquery.py, tests/test_mps_cli_bigquery.py
=> Rename default branch to main

schemas/metadata/decoded/decoded.1.schema.json, schemas/metadata/error/error.1.schema.json, schemas/metadata/pioneer-decoded/pioneer-decoded.1.schema.json, schemas/metadata/pioneer-error/pioneer-error.1.schema.json, schemas/metadata/pioneer-ingestion/pioneer-ingestion.1.schema.json, schemas/metadata/raw/raw.1.schema.json, schemas/metadata/structured-ingestion/structured-ingestion.1.schema.json, schemas/metadata/telemetry-ingestion/telemetry-ingestion.1.schema.json, templates/include/metadata/ingestionCommonMetadata.1.schema.json, templates/include/metadata/raw.1.schema.json
=> Bug 1699080 - Introduce the X-Telemetry-Agent client header

Dockerfile
Fixes https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/681
=> Dockerfile cmake3 -> cmake

README.md
The existing documentation implied you needed to run a full suite of tests even for small changes. This is an unnecessary barrier to entry for people who want to self-serve (e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1715569).
=> Add note about testing to README

schemas/telemetry/crash/crash.4.schema.json, templates/telemetry/crash/crash.4.schema.json, validation/telemetry/crash.4.stackTraces.pass.json
=> Bug 1715087 - Add the newly introduced `unloaded_modules` entry to the crash ping schema

schemas/telemetry/bhr/bhr.4.schema.json, schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/uninstall/uninstall.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json, validation/telemetry/event.4.sample.pass.json
=> Bug 1709383 - Add contentWin32kLockdownState to schema

schemas/telemetry/bhr/bhr.4.schema.json, schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/uninstall/uninstall.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json, validation/telemetry/main.4.sample.pass.json
=> Bug 1709892 - Add hasWinPackageId to environment.

schemas/messaging-system/spotlight/spotlight.1.schema.json, templates/messaging-system/spotlight/spotlight.1.schema.json, validation/messaging-system/spotlight.1.event.pass.json
=> Bug 1728420 - Add a schema for the Messaging System Spotlight template

schemas/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json, templates/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json
See https://mozilla-hub.atlassian.net/browse/DSRE-152
=> Reduce retention on quicksuggest-impression ping

schemas/metadata/decoded/decoded.1.schema.json, schemas/metadata/error/error.1.schema.json, schemas/metadata/pioneer-decoded/pioneer-decoded.1.schema.json, schemas/metadata/pioneer-error/pioneer-error.1.schema.json, schemas/metadata/pioneer-ingestion/pioneer-ingestion.1.schema.json, schemas/metadata/raw/raw.1.schema.json, schemas/metadata/structured-ingestion/structured-ingestion.1.schema.json, schemas/metadata/telemetry-ingestion/telemetry-ingestion.1.schema.json, templates/include/metadata/ingestionCommonMetadata.1.schema.json, templates/include/metadata/raw.1.schema.json
Ref: https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/688
=> Bug 1736466 - Add X-LB-Tags header

schemas/contextual-services/quicksuggest-click/quicksuggest-click.1.schema.json, schemas/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json, schemas/contextual-services/topsites-click/topsites-click.1.schema.json, schemas/contextual-services/topsites-impression/topsites-impression.1.schema.json, schemas/metadata/metaschema/metaschema.1.schema.json, templates/contextual-services/defaults.schema.json, templates/metadata/metaschema/metaschema.1.schema.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1742172 and https://github.com/mozilla/gcp-ingestion/pull/1896
=> Bug 1742172 Add submission_timestamp_granularity metadata

schemas/contextual-services/quicksuggest-click/quicksuggest-click.1.schema.json, schemas/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json, schemas/contextual-services/topsites-click/topsites-click.1.schema.json, schemas/contextual-services/topsites-impression/topsites-impression.1.schema.json, schemas/metadata/metaschema/metaschema.1.schema.json, templates/contextual-services/defaults.schema.json, templates/metadata/metaschema/metaschema.1.schema.json
See https://bugzilla.mozilla.org/show_bug.cgi?id=1742172
The associated pipeline change is in https://github.com/mozilla/gcp-ingestion/pull/1898
=> Bug 1742172 Add override_attributes to metaschema

schemas/telemetry/bhr/bhr.4.schema.json, schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/uninstall/uninstall.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json, validation/telemetry/modules.4.windows.pass.json
=> Bug 1743468 - Add `environment.system.cpu.isWindowsSMode` to ping schemas

.github/auto_assign.yml, .github/pull_request_template.md, CODEOWNERS, README.md
I'm open to any feedback on better or additional places to put this info as well as the content.
Tests are failing with `Too long with no output (exceeded 10m0s): context deadline exceeded`. This document might be moved to mana in a "formal process repository" in early December, so probably worth waiting until that's known to merge this.
=> Codeowners

scripts/mps-build, scripts/mps-test
=> Don't mount entire pwd in mps-tests

schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, templates/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, validation/telemetry/dnssec-study-v1.4.dnsresponses.pass.json, validation/telemetry/dnssec-study-v1.4.emptydnsresponses.pass.json, validation/telemetry/dnssec-study-v1.4.wrongtype.fail.json
=> Bug 1753742 - Update schema for DNSSEC interference study ping to include data for additional queries

schemas/pioneer-sgsb-beyond-the-paywall/page-nav-sensitive/page-nav-sensitive.1.schema.json, templates/pioneer-sgsb-beyond-the-paywall/page-nav-sensitive/page-nav-sensitive.1.schema.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1754056
=> Bug 1754058 - add attentionDuration to beyond the paywall study

schemas/glean/glean/glean.1.schema.json, templates/include/glean/CHANGELOG.md, templates/include/glean/glean.1.schema.json, validation/glean/glean.1.baseline.pass.json, validation/glean/glean.1.events.pass.json, validation/glean/glean.1.invalid_use_counter.fail.json, validation/glean/glean.1.locale.pass.json, validation/glean/glean.1.metrics.pass.json
Fix Glean experiment extra schema and validations
Update changelog
=> Bug 1751739 - Fix Glean experiment `extra` schema

schemas/messaging-system/onboarding/onboarding.1.schema.json, templates/messaging-system/onboarding/onboarding.1.schema.json, validation/messaging-system/onboarding.1.attribution.pass.json
@jklukas Fix of https://bugzilla.mozilla.org/show_bug.cgi?id=1757451
=> Add attribution.dltoken in messaging-system onboarding schema

schemas/telemetry/event/event.4.schema.json, templates/telemetry/event/event.4.schema.json, validation/telemetry/event.4.sample.pass.json
=> [Bug 1748287] Add payload.events.socket to event_v4

schemas/telemetry/crash/crash.4.schema.json, templates/telemetry/crash/crash.4.schema.json
=> Bug 1768225 - UtilityProcess SandboxingKind telemetry

CODEOWNERS, schemas/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json, templates/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json
See https://mozilla-hub.atlassian.net/browse/DSRE-695
=> DSRE-695 Increase retention for quicksuggest-impression

schemas/messaging-system/cfr/cfr.1.schema.json, templates/messaging-system/cfr/cfr.1.schema.json
=> Bug 1777555 - Re-enable messaging_system.cfr

schemas/telemetry/uninstall/uninstall.4.schema.json, templates/telemetry/uninstall/uninstall.4.schema.json
=>  Bug 1765414 - Add top-level type field to uninstall ping schema

schemas/default-browser-agent/default-browser/default-browser.1.schema.json, templates/default-browser-agent/default-browser/default-browser.1.schema.json
Sorry, this was https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/740 but I screwed it up and didn't know how to fix it.
=> Bug 1783722 - Add notification_not_shown_reason to wdba schema

schemas/messaging-system/cfr/cfr.1.schema.json, templates/messaging-system/cfr/cfr.1.schema.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1787882
=> Bug #1787882 - Add `source` column to cfr ping

schemas/glean/glean/glean.1.schema.json, templates/include/glean/custom_distribution.1.schema.json, templates/include/glean/memory_distribution.1.schema.json, templates/include/glean/timing_distribution.1.schema.json, validation/glean/glean.1.metrics.pass.json
=> [Bug 1799509] Add count field to Glean timing_distribution

schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, templates/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, validation/telemetry/dnssec-study-v1.4.dnsresponsesperclient.pass.json, validation/telemetry/dnssec-study-v1.4.emptydnserrorsandresponses.pass.json
=> Updated dnssec-study-v1 to include new per-client and error fields

schemas/telemetry/crash/crash.4.schema.json, scripts/extract_crash_annotation_fields, templates/telemetry/crash/crash.4.schema.json
=> bug 1788681: add FontName and UtilityActorsName to crash ping

schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, templates/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, validation/telemetry/dnssec-study-v1.4.dnsresponsesperclient.pass.json
This is required for a diagnostic experiment.
See https://github.com/mozilla-extensions/dnssec-interference/issues/56
=> dnssec-study-v1.4 updates for new keys and payload data

schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, templates/telemetry/third-party-modules/third-party-modules.4.schema.json, validation/telemetry/third-party-modules.4.sample.pass.json
**I was unable to do this as it says I don't have permission**
- ~~[ ] Update `templates/include/glean/CHANGELOG.md`~~
- ~~[ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)~~
=> Bug 1808158 - Add blockedModules to telemetry's third-party-ping schema

schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, templates/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, validation/telemetry/dnssec-study-v1.4.dnsresponsesv8.pass.json
See mozilla-extensions/dnssec-interference#65
=> Add changes for DNSSEC experiment v8

schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, templates/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, validation/telemetry/dnssec-study-v1.4.dnsresponsesv9.pass.json
See mozilla-extensions/dnssec-interference#69
=> Add changes for dnssec experiment v9

schemas/activity-stream/events/events.1.schema.json, schemas/activity-stream/impression-stats/impression-stats.1.schema.json, schemas/activity-stream/impression-stats/impression-stats.2.schema.json, schemas/activity-stream/on-save-recs/on-save-recs.1.schema.json, schemas/activity-stream/pocket-button/pocket-button.1.schema.json, schemas/activity-stream/sessions/sessions.1.schema.json, schemas/activity-stream/spoc-fills/spoc-fills.1.schema.json, schemas/messaging-system/cfr/cfr.1.schema.json, schemas/messaging-system/infobar/infobar.1.schema.json, schemas/messaging-system/moments/moments.1.schema.json, schemas/messaging-system/onboarding/onboarding.1.schema.json, schemas/messaging-system/personalization-experiment/personalization-experiment.1.schema.json, schemas/messaging-system/snippets/snippets.1.schema.json, schemas/messaging-system/spotlight/spotlight.1.schema.json, schemas/messaging-system/undesired-events/undesired-events.1.schema.json, schemas/messaging-system/whats-new-panel/whats-new-panel.1.schema.json, schemas/metadata/metaschema/metaschema.1.schema.json, templates/activity-stream/defaults.schema.json, templates/messaging-system/defaults.schema.json, templates/metadata/metaschema/metaschema.1.schema.json
=> DENG-547 - Use metadata to indicate source for sample_id

schemas/default-browser-agent/default-browser/default-browser.1.schema.json, schemas/firefox-installer/install/install.1.schema.json, templates/default-browser-agent/default-browser/default-browser.1.schema.json, templates/firefox-installer/install/install.1.schema.json
=> DENG-547 - Make sample_id useful for default_browser_agent and firefox_installer

README.md
just a quick update in the README for the brew cask command 
=> update brew command in README

schemas/pioneer-sgsb-beyond-the-paywall/advertisement/advertisement.1.schema.json, schemas/pioneer-sgsb-beyond-the-paywall/article-content/article-content.1.schema.json, schemas/pioneer-sgsb-beyond-the-paywall/page-nav-sensitive/page-nav-sensitive.1.schema.json, schemas/pioneer-sgsb-beyond-the-paywall/page-nav/page-nav.1.schema.json, schemas/pioneer-sgsb-beyond-the-paywall/total-timing/total-timing.1.schema.json, templates/pioneer-sgsb-beyond-the-paywall/advertisement/advertisement.1.schema.json, templates/pioneer-sgsb-beyond-the-paywall/article-content/article-content.1.schema.json, templates/pioneer-sgsb-beyond-the-paywall/page-nav-sensitive/page-nav-sensitive.1.schema.json, templates/pioneer-sgsb-beyond-the-paywall/page-nav/page-nav.1.schema.json, templates/pioneer-sgsb-beyond-the-paywall/total-timing/total-timing.1.schema.json
https://mozilla-hub.atlassian.net/browse/DSRE-1322
=> Remove delete_after_days from pioneer sgsb study

schemas/glean/glean/glean.1.schema.json, templates/include/glean/CHANGELOG.md, templates/include/glean/dot_separated_short_id.1.schema.json
=> Bug 1849615 - Update schema for dot_separated_short_id.

Dockerfile
=> Update rust version to fix CI

schemas/telemetry/bhr/bhr.4.schema.json, schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/sync/sync.4.schema.json, schemas/telemetry/sync/sync.5.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/uninstall/uninstall.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json, templates/include/telemetry/syncPayload.1.schema.json
=> Bug 1874038 - Add environment.os.distro/distroVersion to table schemas

schemas/default-browser-agent/default-browser/default-browser.1.schema.json, templates/default-browser-agent/default-browser/default-browser.1.schema.json
Follow-up to https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/802#issuecomment-1896282461
=> Add previous_os_version to default-browser-agent/default-browser.

schemas/telemetry/bhr/bhr.4.schema.json, schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/uninstall/uninstall.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json
=> Bug 1845596 - Update telemetry event schema json

schemas/glean/glean/glean.1.schema.json, schemas/metadata/metaschema/metaschema.1.schema.json, templates/glean/defaults.schema.json, templates/include/glean/glean.1.schema.json, templates/include/glean/object.1.schema.json, templates/metadata/metaschema/metaschema.1.schema.json
=> Bug 1839640 - Add the object type with very shallow restrictions

schemas/telemetry/bhr/bhr.4.schema.json, schemas/telemetry/crash/crash.4.schema.json, schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json, schemas/telemetry/event/event.4.schema.json, schemas/telemetry/first-shutdown/first-shutdown.4.schema.json, schemas/telemetry/heartbeat/heartbeat.4.schema.json, schemas/telemetry/main/main.4.schema.json, schemas/telemetry/modules/modules.4.schema.json, schemas/telemetry/new-profile/new-profile.4.schema.json, schemas/telemetry/saved-session/saved-session.4.schema.json, schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json, schemas/telemetry/testpilot/testpilot.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, schemas/telemetry/uninstall/uninstall.4.schema.json, schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json, schemas/telemetry/update/update.4.schema.json, schemas/telemetry/voice/voice.4.schema.json, templates/include/telemetry/environment.1.schema.json
=> Bug 1896975 - Add `signedState` and `signedTypes` for the active theme to the environment schema

schemas/telemetry/downgrade/downgrade.4.schema.json, schemas/telemetry/sync/sync.4.schema.json, schemas/telemetry/third-party-modules/third-party-modules.4.schema.json, templates/telemetry/downgrade/downgrade.4.schema.json, templates/telemetry/sync/sync.4.schema.json, templates/telemetry/third-party-modules/third-party-modules.4.schema.json
https://mozilla-hub.atlassian.net/browse/DSRE-1838?focusedCommentId=977229
https://mozilla-hub.atlassian.net/browse/DSRE-1831?focusedCommentId=976136
https://mozilla-hub.atlassian.net/browse/DSRE-1833?focusedCommentId=977341
=> Metadata updates

schemas/glean/glean/glean-min.1.schema.json, schemas/glean/glean/glean.1.schema.json, templates/include/glean/metrics.1.schema.json, validation/glean/glean.1.metrics.pass.json
=> Bug 1957085 - Add dual labeled counter metric type
