telemetry/crash.schema.json

- Swith the patterns to the rapidjson regex subset
- Allow many items to be NULL to prevent more than a 50% rejection rate
- new rejection rate is about 1%

Adjust the schemas to work with the sandbox validation

---

telemetry/main.schema.json
validation/telemetry/sample_v4_ping.json

This adds the application.displayVersion property; leaving it optional
for now until we figure out versioning.
This also updates the validation sample to show-case the difference in
version numbers.

Add application.displayVersion and environment.settings.e10sCohort for "main" pings

---

telemetry/core.schema.json

The "meta" section is not being validated in this schema. Should the meta bits be added server-side?

Add a schema for Fennec "core" pings.

---

telemetry/main.schema.json
validation/telemetry/sample_v4_ping.json

Bug 1259139 [0] adds an origin property to
environment.settings.defaultSearchSearchEngineData, this updates the
main ping schema for it.

Add defaultSearchEngineData.origin

---

telemetry/main.schema.json

This is an improvement. I'm not familiar with this so you might want to review it carefully.
I left opengl/webgl/d2d/d3d11 as object but they will have an optional sub field 'failureId' that I'd really like to get into the dataset. But they also have a lot of other datafields. I think that's what the ["string", "null"] type might be but I wasn't sure.
I'm also not sure how to test this change?

Add graphic fields

---

metadata/metadata_sources.schema.json

AFAIK this isn't enforced anywhere, but should be updated for schema completeness regarding https://bugzilla.mozilla.org/show_bug.cgi?id=1302264.
@mreid-moz r?

Add protobuf.gzip to record_format

---

telemetry/core.schema.json

This patch introduces three fields for Firefox for iOS:
* `defaultSearch` - The search engine that the user has selected
* `defaultMailClient` - The mail client that the user prefers to use
* `defaultNewTabExperience` - What the user prefers to see when opening a new tab
The `defaultSearch` field was actually introduced in the iOS Core Ping earlier this year. The `core.schema.json` was never updated for it though.

Update core.schema with new Firefox for iOS fields

---

telemetry/main.schema.json
validation/telemetry/sample_v4_ping.json

This addresses bug 1314231:
https://bugzilla.mozilla.org/show_bug.cgi?id=1314231
Bug 1304494 added support for Telemetry accumulations from the GPU
process, this adds them to the main ping schema:
https://bugzilla.mozilla.org/show_bug.cgi?id=1304494
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/17)

Add gpu process histograms to main ping schema

---

telemetry/crash.schema.json

There are many other valid values for `channel`. Relax this requirement, similar to [this commit](https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/1149cb7a7f356f1a9888c664a805f2434823b7ef) for `main` pings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/23)

Don't enumerate specific channels for crash pings.

---

telemetry/crash.schema.json

Some crash pings have a clientId field, but with a value of null.
Relax the schema to allow for these pings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/24)

Allow null for clientId in crash pings.

---

telemetry/core.schema.json
validation/telemetry/core_v7_ping.json

This seems to have fallen behind the current core ping version. Ordering is the same as the docs [0].
[0] https://gecko.readthedocs.io/en/latest/toolkit/components/telemetry/telemetry/data/core-ping.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/37)

Core schema update

---

telemetry/anonymous.schema.json
telemetry/core.schema.json

"name" isn't in json schema definition, but "title" is.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/39)

Change name to title

---

telemetry/focus-event.parquetmr.txt
telemetry/focus-event.schema.json
validation/telemetry/focus_event_v1.json

I've tested the JSON with a schema validator. I've tested the parquet on hsadmin. Both look good, parquet output is readable in Spark and contains all columns.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/mozilla-pipeline-schemas/43)

Bug 1353796 - Add Focus events ping schema

---

schemas/telemetry/main/main.4.schema.json
validation/telemetry/sample_v4_ping.json

This is per https://bugzilla.mozilla.org/show_bug.cgi?id=1339195#c3
Extra objects for events are restricted to string keys and string
values.

Restrict event extra values to strings

---

schemas/telemetry/main/main.4.schema.json

Can `subsessionLength` be 0 or null?

Bug 1357043 - Disallow negative subsessionLength

---

schemas/telemetry/new-profile/new-profile.4.schema.json
validation/telemetry/new-profile_v4_ping.json
validation/telemetry/validate_main.py

This just checks in the schema using the "old" process, bringing in a copy of the environment in the schema. The 'new-profile' ping is being deployed, so I'm not sure we should block on #47 or #46 .

Add a schema for the 'new-profile' ping

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json

The metadata for each ping is not added on the client, so
we don't need to have a "meta" object in these schemas.

Remove the "meta" object from the ping schemas

---

schemas/telemetry/new-profile/new-profile.4.schema.json

This is the final demonstration that copy/pasting does not solve all the problems in the world.

Make environment, payload and clientId mandatory

---

schemas/telemetry/focus-event/focus-event.1.parquetmr.txt
schemas/telemetry/focus-event/focus-event.1.schema.json
validation/telemetry/focus-event.1.error.json

This allows null values in 3 places:
1. As values in the settings map
2. As values in the Events list
3. As values in the extra field of the Events list
The schema validates against the example. @trink can you take a peek at the parquet schema and make sure it seems correct?

Bug 1382223 - Allow null values in focus-event ping

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/main.4.sample.json

This PR also contains the update schemas and an update main ping sample. The generated schema validates correctly against the example.
I'm not sure why the generation step also changed `focus-event`. Looks like this is reverting the hotfix from 89a43b8? @fbertsch , any clue?

Enable schema validation for environment.experiments

---

schemas/heka/telemetry/telemetry_errors.1.parquetmr.txt
templates/heka/telemetry/telemetry_errors.1.parquetmr.txt
tests/hindsight/run/input/test_heka_messages.lua

Rename landfill_errors to telemetry_errors, and make several fields optional.
This still needs to be tested - there appears to be some unrelated test bustage from pioneer stuff.

Bug 1400934 - Rename landfill_errors, make fields optional

---

schemas/heka/telemetry/telemetry_duplicates.1.parquetmr.txt
templates/heka/telemetry/telemetry_duplicates.1.parquetmr.txt

We can remove it like this or make it optional to keep schema compatibility. As the data was kind of mucked up anyway before this week I'm not sure if it matters.

Drop normalizedChannel from telemetry_duplicates

---

schemas/mozza/event/event.1.schema.json
schemas/telemetry/focus-event/focus-event.1.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/mobile-event/mobile-event.1.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
templates/include/common/event.1.schema.json
templates/include/telemetry/mobileEvent.1.schema.json
templates/include/telemetry/processData.1.schema.json
templates/mozza/event/event.1.schema.json
validation/mozza/event.1.sample.json

Considerations:
- The partitioning column will be `property`, e.g. "which web property is sending this data?" but I'm not attached to that name. Alternatives could be simply partitioning by base URL.
- We could add more dimensional information; a good one might be some sort of user or session id (for eventual funnel analyses)
- Moved to a common event JSON schema
- The parquet schema will be written when we finalize what this data will look like

WIP: mozza events

---

schemas/mozza/event/event.1.parquetmr.txt
schemas/telemetry/focus-event/focus-event.1.parquetmr.txt
schemas/telemetry/mobile-event/mobile-event.1.parquetmr.txt
templates/include/common/event.1.parquetmr.txt
templates/mozza/event/event.1.parquetmr.txt
templates/telemetry/focus-event/focus-event.1.parquetmr.txt
templates/telemetry/mobile-event/mobile-event.1.parquetmr.txt

:whd, just want to make sure that d2p for moz_ingest will work similarly. It seems all of those metadata fields are available. Feel free to reassign reviewers if you're busy.

Add mozza event parquet output

---

schemas/mozza/event/event.1.parquetmr.txt
templates/mozza/event/event.1.parquetmr.txt

The date header is not supported in either fetch or sendBeacon.

Make mozza date header optional

---

schemas/telemetry/focus-event/focus-event.1.parquetmr.txt
schemas/telemetry/focus-event/focus-event.1.schema.json
schemas/telemetry/mobile-event/mobile-event.1.parquetmr.txt
schemas/telemetry/mobile-event/mobile-event.1.schema.json
templates/include/telemetry/mobileEvent.1.schema.json
templates/telemetry/focus-event/focus-event.1.parquetmr.txt
templates/telemetry/focus-event/focus-event.1.schema.json
templates/telemetry/mobile-event/mobile-event.1.parquetmr.txt
templates/telemetry/mobile-event/mobile-event.1.schema.json
validation/telemetry/mobile-event.1.error.json
validation/telemetry/mobile-event.1.sample.json

This can be used in reporting to convert event timestamps from being relative to the process start time to being standard absolute timestamps.

Add 'processStartTimestamp' as a required field for mobile-event and an optional field for focus-event.

---

schemas/heka/pioneer-study/pioneer_errors.1.parquetmr.txt
templates/heka/pioneer-study/pioneer_errors.1.parquetmr.txt

This is the same as the telemetry errors parquet schema but with the omission of submissionDate (legacy telemetry decoder behavior not present in pioneer decoding) and the addition of some optional pioneer-specific fields.

Add pioneer study errors parquet schema

---

schemas/telemetry/main/main.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
templates/include/common/event.1.schema.json
templates/include/telemetry/histogram.1.schema.json
templates/include/telemetry/mainPayload.1.schema.json
templates/include/telemetry/processData.1.schema.json

There were a few sub-sections that had extra key names and such that resulted in them not properly being applied (so any "object" data would pass validation).
This PR ensures that `events`, `histograms`, and `scalars` sections are validated.
There is risk with this change, as we are effectively making the validation significantly more strict.

Ensure that sections of the schema are being used

---

schemas/pioneer-study/online-news-log.2.parquetmr.txt
schemas/pioneer-study/online-news-log.2.schema.json
templates/pioneer-study/online-news-log.2.parquetmr.txt
templates/pioneer-study/online-news-log.2.schema.json

This reverts commit 971e56893fe2c008782f6ae3bfe71e6ac533356b.
Fixes schema validation errors caused by v1 log entries being sent with v2 pings

Revert "Make branch required"

---

schemas/telemetry/mobile-event/mobile-event.1.parquetmr.txt
templates/telemetry/mobile-event/mobile-event.1.parquetmr.txt

co-dependent on mozilla-services/puppet-config#2725

Bug 1455385 - Move mobile-event 'os' to partitions

---

schemas/telemetry/core/core.9.parquetmr.txt
templates/telemetry/core/core.9.parquetmr.txt

co-dependent on mozilla-services/puppet-config#2726

Bug 1455383 - Change core ping partitions

---

.dockerignore

Add a .dockerignore file to skip the CMake cache.

---

schemas/telemetry/shield-study-addon/shield-study-addon.3.parquetmr.txt
schemas/telemetry/shield-study-error/shield-study-error.3.parquetmr.txt
schemas/telemetry/shield-study/shield-study.3.parquetmr.txt
templates/telemetry/shield-study-addon/shield-study-addon.3.parquetmr.txt
templates/telemetry/shield-study-error/shield-study-error.3.parquetmr.txt
templates/telemetry/shield-study/shield-study.3.parquetmr.txt

This is optional everywhere else and we see occasionally clients sending data without this header.

Make shield-study Date header metadata optional

---

schemas/eng-workflow/hgpush/hgpush.1.schema.json
templates/eng-workflow/hgpush/hgpush.1.schema.json
validation/eng-workflow/hgpush.1.landingSystem_null.pass.json

Allow the hgpush ping schema's landingSystem field to be null.

Allow hgpush landingSystem to be null

---

validation/telemetry/main.4.good_histogram.pass.json
validation/telemetry/main.4.negative_count.fail.json

Add a minimal passing histogram, a failure due to a negative count, and simplify the failure case for an invalid bucket key pattern.

Add a couple more histogram validation examples.

---

README.md

The created container is only used for a single test run and never reused. It however persists on the user's machine until its deleted. Let's just remove it immediately after running the tests.

Automatically remove the test container when it exits

---

schemas/telemetry/frecency-update/frecency-update.4.schema.parquetmr.txt
templates/telemetry/frecency-update/frecency-update.4.schema.parquetmr.txt

This PR adds the `Timestamp` field to the Parquet schema, for easier analysis after the study ends.

Add Timestamp to frecency-update

---

schemas/eng-workflow/build/build.1.parquetmr.txt
schemas/eng-workflow/build/build.1.schema.json
templates/eng-workflow/build/build.1.parquetmr.txt
templates/eng-workflow/build/build.1.schema.json
validation/eng-workflow/build.1.sample.pass.json

This commit adds a schema for build system telemetry data
collection in both json-schema and Parquet formats. The
schema is added under the eng-workflow namespace. The
datareview+ for this new ping was received in bug 1291053.

Bug 1237610: add schemas for build system telemetry

---

schemas/telemetry/block-autoplay/block-autoplay.1.schema.json
templates/telemetry/block-autoplay/block-autoplay.1.schema.json
validation/telemetry/block-autoplay.1.counters.pass.json
validation/telemetry/block-autoplay.1.prompt.pass.json
validation/telemetry/block-autoplay.1.settings.pass.json

We would send the custom telemetry ping from block-autoplay shield-study extension [1] which is used to analysis the user behavior when they interact with the block-autoplay prompt and setting.
This custom ping also pass the data review [2].
[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1475099
[2] https://bugzilla.mozilla.org/show_bug.cgi?id=1479589

block-autoplay JSON schema and validation tests.

---

schemas/telemetry/block-autoplay/block-autoplay.1.schema.json
templates/telemetry/block-autoplay/block-autoplay.1.schema.json
validation/telemetry/block-autoplay.1.prompt.pass.json

After discussed with our data scientist, adding two new attributes `interact` and `responseTime` in `promptResponse` object.
`interact` is used to answer how user interacts with the prompt.
`responseTime` is the total showing time before the promp dismiss.
See the full explanation document [here](https://github.com/alastor0325/autoplay-shield-study/blob/develop/docs/TELEMETRY.md#block-autoplay-pings-specific-to-this-study).

add attributes `interact` and `responseTime` in `promptResponse` object.

---

.circleci/config.yml
.travis.yml

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1458734#c1)
This PR tests schemas against real, sampled data. A report is generated between the `HEAD` of the PR and `mozilla:dev`. The sampled data (`sanitized-landfill-sample`) is generated by a scheduled batch job under a stricter IAM role with access to landfill data. The CI takes advantage of a script included in the `mozilla/edge-validator` docker image to generate integration reports and diffs between two revisions of mozilla-pipeline-schemas. If there is a change in the report (e.g. a decrease in validation errors on a doctype), a diff is generated and added as a test artifact that can be reviewed.
This moves from TravisCI to CircleCI to support more complex workflows. I wrote some test cases in [this PR on my local …

Bug 1458734 - Test schemas against real sampled data using edge-validator

---

schemas/telemetry/main/main.4.schema.json
schemas/telemetry/mobile-metrics/mobile-metrics.1.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
templates/include/telemetry/histogram.1.schema.json

This uses the more strict subset of regex that's recommended in [Understanding JSON Schema](https://json-schema.org/understanding-json-schema/reference/regular_expressions.html) tutorial.
The python wrapper for rapidjson doesn't include the `std::regex` at compile time to support `\d`, but square brackets suffice. This should make the schemas more widely compatible and will fix the validation errors in the `edge-validator` server.

Use `[0-9]` instead of `\d` in histograms

---

schemas/coverage/coverage/coverage.1.parquetmr.txt
schemas/coverage/coverage/coverage.1.schema.json
templates/coverage/coverage/coverage.1.parquetmr.txt
templates/coverage/coverage/coverage.1.schema.json
validation/coverage/coverage.1.extra_field.fail.json
validation/coverage/coverage.1.missing_field.fail.json
validation/coverage/coverage.1.sample.pass.json

See also [the PR for the add-on sending this ping](https://github.com/mozilla/one-off-system-add-ons/pull/123).

Bug 1487578 - Add schemas for "coverage" ping

---

.circleci/config.yml
README.md

This shortcuts the CircleCI integrate step to fix currently broken tests. This also documents how to manually run integration tests against real data using the working directory.

Update CircleCI and document edge-validator integration tests

---

schemas/telemetry/main/main.4.schema.json
schemas/telemetry/mobile-metrics/mobile-metrics.1.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
templates/include/telemetry/mainPayload.1.schema.json
templates/include/telemetry/metricsData.1.schema.json

Keyed histograms are represented as doubly-nested maps. The first level of nested is missing the `"type": "object"` field, which was breaking a script.

Add proper typing for keyedHistograms

---

schemas/telemetry/untrusted-modules/untrusted-modules.4.parquetmr.txt
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
templates/telemetry/untrusted-modules/untrusted-modules.4.parquetmr.txt
templates/telemetry/untrusted-modules/untrusted-modules.4.schema.json
validation/telemetry/untrusted-modules.4.minimal.pass.json
validation/telemetry/untrusted-modules.4.moduletrustflags.fail.json
validation/telemetry/untrusted-modules.4.sample.pass.json
validation/telemetry/untrusted-modules.4.stackframe.fail.json

This adds the necessary validation and ingestion schemas for the new "Untrusted Modules" ping introduced in Bug 1435827, along with basic test payloads.
The schema includes the telemetry ping environment block, which is essentially a port of /templates/include/telemetry/environment.1.schema.json, minus the following structures because of the difficulty in representing in parquet:
- userPrefs
- activeAddons/userDisabled
- activeAddons/foreignInstall
- activeGMPlugins/applyBackgroundUpdates
- theme/foreignInstall
- activeAddons/version
- system/os/version
- experiments

Bug 1435827: Adding JSON and Parquet schemas

---

schemas/glean/baseline/baseline.1.schema.json
templates/include/glean/glean.1.schema.json
validation/glean/baseline.1.all.pass.json

Given [1507788](https://bugzilla.mozilla.org/show_bug.cgi?id=1507788), we need to support dots within the metric category name.  Therefore the `category.name` notation used to identify metrics can now have multiple dots.  This broadens the regex used to validate the metric name to support that.

1507788: Support dots in category part of dotted notation

---

schemas/glean/baseline/baseline.1.schema.json
templates/include/glean/glean.1.schema.json
validation/glean/baseline.1.all.pass.json
validation/glean/baseline.1.core.pass.json

This changes how events are stored in the glean ping to follow [how they are on desktop](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/collection/events.html#serialization-format)

Store events as we do on desktop

---

schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
templates/telemetry/untrustedModules/untrustedModules.4.schema.json
validation/telemetry/untrustedModules.4.unknownmodule.pass.json

The previous schema specified 0 as the minimum value for this field, but -1
should also pass validation.
A value of -1 indicates that the address does not fall in any known module.
See also:
* Documentation: https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/untrusted-modules-ping.html#payload-combinedstacks
* The value of -1 is generated here: https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/other/CombinedStacks.cpp#206
* And the underlying logic for this value comes from: and https://searchfox.org/mozilla-central/rev/e22c0d152060f4f8d4ca8904094f15f65a1b6f93/toolkit/components/telemetry/other/ProcessedStack.cpp#141

Allow -1 value for untrustedModules / moduleIndex field (#226)

---

schemas/activity-stream/impression-stats/impression-stats.1.schema.json
templates/activity-stream/impression-stats/impression-stats.1.schema.json
validation/activity-stream/impression-stats.1.sample.pass.json

Implements a schema matching the existing ping-centre payloads defined in
https://github.com/mozilla/activity-stream/blob/master/docs/v2-system-addon/data_events.md#top-story-pings
Should allow double-publishing of payloads via ping-centre and via telemetry.

WIP: Add activity-stream impression-stats schema

---

.circleci/config.yml
.github/pull_request_template.md
.github/push-to-trigger-integration
README.md

Also adds caching of the data from S3, which brings runtime for the integration test down to ~60 seconds.

Bug 1503256 Add pull request template with reviewer instructions

---

schemas/telemetry/untrustedModules/untrustedModules.4.parquetmr.txt
templates/telemetry/untrustedModules/untrustedModules.4.parquetmr.txt

For the untrusted modules ping, data under environment/system is not coming
through in redash. This corrects the nesting of objects under environment/system
in order to fix this.
Sorry for the ugly diff; it's just a moved closing brace and an indent =)

Bug 1515029: Fix untrusted modules ping environment block nesting

---

schemas/telemetry/untrustedModules/untrustedModules.4.parquetmr.txt
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
templates/telemetry/untrustedModules/untrustedModules.4.parquetmr.txt
templates/telemetry/untrustedModules/untrustedModules.4.schema.json
validation/telemetry/untrustedModules.4.sample.pass.json

This modifies the untrusted modules ping Parquet and JSON schemas to add 2 new
fields:
- "xulLoadDurationMS" (optional, number) at the payload root
- "loadDurationMS" (optional, number) per module object
And adds these fields to validation schema: untrustedModules.4.sample.pass.json
These fields are marked optional in order to be compatible with the previous
schema.
The code that generates these fields landed in
https://hg.mozilla.org/mozilla-central/rev/1b1fe5815dff

Bug 1518490: Add pipeline schemas for 2 new timing fields in untrusted modules ping

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/main.4.intl_alldata.pass.json
validation/telemetry/main.4.intl_nosection.pass.json
validation/telemetry/main.4.intl_null.fail.json
validation/telemetry/main.4.intl_null.pass.json

CC @mstriemer
Bug 1502921 added a few field to the Environment ping. Per IRC discussion, we need this data to be validated in order to add it to datasets in STMO.
Landing in m-c (Firefox 66): https://hg.mozilla.org/mozilla-central/rev/de6426e0f491

Bug 1502921 - Add new 'intl' fields to environment data schema

---

schemas/telemetry/modules/modules.4.parquetmr.txt
schemas/telemetry/modules/modules.4.schema.json
templates/telemetry/modules/modules.4.parquetmr.txt
templates/telemetry/modules/modules.4.schema.json
validation/telemetry/modules.4.windows.pass.json

This adds the additional optional "certSubject" field to the modules ping
schemas, and updates the Windows validation test accordingly.
The "certSubject" field was already present in the payload sent from clients,
but it was not available in redash. This patch aims to correct that.

Bug 1524291 Add certSubject to modules ping schemas

---

.github/push-to-trigger-integration

Fix printed integration branch location

---

schemas/glean/baseline/baseline.1.schema.json
schemas/glean/events/events.1.schema.json
schemas/glean/metrics/metrics.1.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json
schemas/org-mozilla-reference-browser/events/events.1.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json
schemas/org-mozilla-samples-glean/events/events.1.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json
templates/include/glean/glean.1.schema.json

This just removes an extraneous newline in a description (that I think is an artifact of the original version of this schema being written in YAML).

Remove extraneous newline

---

schemas/glean/baseline/baseline.2.schema.json
schemas/glean/events/events.2.schema.json
schemas/glean/metrics/metrics.2.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.2.schema.json
schemas/org-mozilla-reference-browser/events/events.2.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.2.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.2.schema.json
schemas/org-mozilla-samples-glean/events/events.2.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.2.schema.json
schemas/telemetry/heartbeat/heartbeat.4.parquetmr.txt
schemas/telemetry/heartbeat/heartbeat.4.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/glean.2.schema.json

I feel like `ping_info` should be pretty locked down, since we want to be able to rely on exactly what's in there for every single ping.  This is in contrast to even things in the baseline ping where end-user code can add custom pings to the `metrics` section by design.  This has already been the source of [one bug](https://github.com/mozilla-mobile/android-components/pull/1984#discussion_r254739261) that slipped through the cracks.

[glean] Don't allow additionalProperties in ping_info

---

schemas/webpagetest/webpagetest-run/webpagetest-run.1.parquetmr.txt
templates/webpagetest/webpagetest-run/webpagetest-run.1.parquetmr.txt

This fixes metric field mapping in Parquet schema - we were missing one level of nesting (representing measurement type).
Relevant part of the ping: https://github.com/mozilla-services/mozilla-pipeline-schemas/blob/dev/validation/webpagetest/webpagetest-run.1.sample.pass.json#L8-L14

Fix Webpagetest parquet schema

---

schemas/pocket/fire-tv-events/fire-tv-events.1.parquetmr.txt
templates/pocket/fire-tv-events/fire-tv-events.1.parquetmr.txt

This field isn't queryable and borks the whole metadata section: ` Parquet type FIXED_LEN_BYTE_ARRAY supported as DECIMAL; got null`.
We'll need to bump the version with this change.

Remove Uuid from fire-tv metadata

---

schemas/glean/baseline/baseline.1.schema.json
schemas/glean/baseline/baseline.2.schema.json
schemas/glean/events/events.1.schema.json
schemas/glean/events/events.2.schema.json
schemas/glean/metrics/metrics.1.schema.json
schemas/glean/metrics/metrics.2.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.2.schema.json
schemas/org-mozilla-reference-browser/events/events.1.schema.json
schemas/org-mozilla-reference-browser/events/events.2.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.2.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.2.schema.json
schemas/org-mozilla-samples-glean/events/events.1.schema.json
schemas/org-mozilla-samples-glean/events/events.2.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.2.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/labeled_group.1.schema.json

This broadens the `label` regex so it can include `.` and `/`.  This is needed for [error tracking](https://bugzilla.mozilla.org/show_bug.cgi?id=1499761).  Error tracking uses labeled counters where the label is the fully-qualified name of the metric associated with the error, and those have `.` in them.  Additionally the metric that caused the error may itself be a labeled metric, therefore it could have a `/` in it.
This is entirely independent of the allowed labels when using labeled metrics directly on the client, which still doesn't allow these characters.

Loosen label regex

---

schemas/glean/baseline/baseline.2.parquetmr.txt
schemas/glean/baseline/baseline.2.schema.json
schemas/glean/events/events.2.parquetmr.txt
schemas/glean/events/events.2.schema.json
schemas/glean/metrics/metrics.2.parquetmr.txt
schemas/glean/metrics/metrics.2.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.2.parquetmr.txt
schemas/org-mozilla-reference-browser/baseline/baseline.2.schema.json
schemas/org-mozilla-reference-browser/events/events.2.parquetmr.txt
schemas/org-mozilla-reference-browser/events/events.2.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.2.parquetmr.txt
schemas/org-mozilla-reference-browser/metrics/metrics.2.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.2.parquetmr.txt
schemas/org-mozilla-samples-glean/baseline/baseline.2.schema.json
schemas/org-mozilla-samples-glean/events/events.2.parquetmr.txt
schemas/org-mozilla-samples-glean/events/events.2.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.2.parquetmr.txt
schemas/org-mozilla-samples-glean/metrics/metrics.2.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/event.1.schema.json
templates/include/glean/glean.2.parquetmr.txt
templates/include/glean/glean.2.schema.json
validation/glean/baseline.2.all.pass.json
validation/glean/baseline.2.core.pass.json
validation/glean/events.2.all.pass.json

This adds the glean specific event format to the templates, since it differs from the desktop ones.
We're dropping object/value, renaming `method` to `name` (as we're dropping the "method" special case too), and keeping `extra` as optional.
I've not bumped the ping schema version, as we don't really care about the old data (there should be none, except from the samples). But I'm happy to address this, if needed.

Implement the new events API schema

---

.circleci/config.yml

This adds simple check to verify that all generated schemas are committed.
Process consists of:
1. Generating schemas
2. Checking git for any untracked files under `schemas*`
Sample error output can be observed here: https://circleci.com/gh/mozilla-services/mozilla-pipeline-schemas/632

Bug 1383111 - Add build step to validate if all generated schemas are committed

---

schemas/glean/baseline/baseline.1.schema.json
schemas/glean/events/events.1.schema.json
schemas/glean/metrics/metrics.1.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json
schemas/org-mozilla-reference-browser/events/events.1.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json
schemas/org-mozilla-samples-glean/events/events.1.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json

This fixes the "Inconsistencies between templates and rendered schemas" [error here](https://circleci.com/gh/mozilla-services/mozilla-pipeline-schemas/670?utm_campaign=workflow-failed&utm_medium=email&utm_source=notification) caused after merging #275.
I'm sure it was just human error (this human) that caused the issue -- but is there something that should have caught that pre-merge?

Fix inconsistencies between template and builds

---

schemas/telemetry/frecency-update/frecency-update.4.parquetmr.txt
schemas/telemetry/frecency-update/frecency-update.4.schema.json
templates/telemetry/frecency-update/frecency-update.4.parquetmr.txt
templates/telemetry/frecency-update/frecency-update.4.schema.json
validation/telemetry/frecency-update.4.sample.pass.json

For the relaunch of the federated learning study: https://github.com/mozilla/federated-learning-v2-study-addon
In this PR, I chose to overwrite the existing `frecency-update` ping rather than introducing `frecency-update-v2` or similar since the `frecency-update` pings from v1 of the study should no longer be consumed.

Updated frecency-update to match the v2 implementation

---

tests/hindsight/run/input/test_json_schemas.lua
validation/glean/metrics.1.null_timespan.fail.json

This adds a test to ensure that `null` timespans in glean are rejected by the JSON schema.
This includes a small workaround for the test harness so that failing JSON tests are not passed along for a parquet test (where there is currently no provision to handle failing tests).
Related to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1525600)

[glean] NULL timespan checks

---

tests/hindsight/run/input/test_json_schemas.lua

Fix PR #280 - Skip the injection on failure instead of aborting the test

---

schemas/telemetry/main/main.4.schema.json
schemas/telemetry/mobile-metrics/mobile-metrics.1.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
templates/include/telemetry/histogram.1.schema.json
templates/include/telemetry/mainPayload.1.schema.json

This fixes #288 by adding a fuller type definition for arrays. The missing fields were found by using the following script:
https://gist.github.com/acmiyaguchi/0786d0cff8d79f8a9662377ad3e891b1
Then running the following command at the toplevel:
```
find schemas/ -name "*.schema.json" | xargs -I {} bash -c "echo {}; cat {} | python3 find-arrays.py" 
```

Add better definitions for array types missing items

---

schemas/telemetry/main/main.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
templates/include/telemetry/gcItem.1.schema.json

This adds the missing array items field to the gc slices, while retaining the variant numeric type. The object is the more recent of the two variants, introduced in ff58.
```
jq '.. | select(.gc?) | .gc.random[].slices, .gc.worst[].slices | type' data/telemetry.main.4.ndjson | sort | uniq -c 
16 "array"
84 "number"
```
re:
https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/291#issuecomment-474380070
https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/291#issuecomment-474814119

Add items for gcItems

---

schemas/glean/baseline/baseline.1.parquetmr.txt
schemas/glean/baseline/baseline.1.schema.json
schemas/glean/events/events.1.parquetmr.txt
schemas/glean/events/events.1.schema.json
schemas/glean/metrics/metrics.1.parquetmr.txt
schemas/glean/metrics/metrics.1.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.1.parquetmr.txt
schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json
schemas/org-mozilla-reference-browser/events/events.1.parquetmr.txt
schemas/org-mozilla-reference-browser/events/events.1.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.1.parquetmr.txt
schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.1.parquetmr.txt
schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json
schemas/org-mozilla-samples-glean/events/events.1.parquetmr.txt
schemas/org-mozilla-samples-glean/events/events.1.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.1.parquetmr.txt
schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json
templates/include/glean/glean.1.parquetmr.txt
templates/include/glean/glean.1.schema.json
validation/glean/baseline.1.all.pass.json
validation/glean/events.1.all.pass.json
validation/glean/metrics.1.all.pass.json
validation/glean/metrics.1.null_timespan.fail.json

This additionally changes fields in `ping_info` and `client_info` to use the glean templates, where available, as done with other metrics. Since we're pre-data-reliance, I'm not bumping the schema version.
@fbertsch should I still add an entry to the changelog?

Split some fields out of gleans'`ping_info` to `client_info`

---

schemas/eng-workflow/build/build.1.parquetmr.txt
schemas/eng-workflow/build/build.1.schema.json
templates/eng-workflow/build/build.1.parquetmr.txt
templates/eng-workflow/build/build.1.schema.json
validation/eng-workflow/build.1.buildAttrs.pass.json

This pr adds two fields to built system telemetry. datareview was granted in bug 1526072.

Bug 1526072 - Add fields for clobber builds and resource utilization to build telemetry

---

schemas/activity-stream/impression-stats/impression-stats.1.schema.json
templates/activity-stream/impression-stats/impression-stats.1.schema.json
validation/activity-stream/impression-stats.1.loadedContent.pass.json

This adds an optional integer field "loaded" to `activity-stream.impression-stats`.
r? @jklukas

Bug 1530740 - Add "loaded" to activity-stream.impression-stats

---

README.md

parquetfmt is not released on crates.io.
We could either change that or explain how to install it from git.
r?@trink

Fix docs to explain how to install parquetfmt from git

---

schemas/glean/baseline/baseline.1.parquetmr.txt
schemas/glean/baseline/baseline.1.schema.json
schemas/glean/events/events.1.parquetmr.txt
schemas/glean/events/events.1.schema.json
schemas/glean/metrics/metrics.1.parquetmr.txt
schemas/glean/metrics/metrics.1.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.1.parquetmr.txt
schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json
schemas/org-mozilla-reference-browser/events/events.1.parquetmr.txt
schemas/org-mozilla-reference-browser/events/events.1.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.1.parquetmr.txt
schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.1.parquetmr.txt
schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json
schemas/org-mozilla-samples-glean/events/events.1.parquetmr.txt
schemas/org-mozilla-samples-glean/events/events.1.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.1.parquetmr.txt
schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json
templates/include/glean/glean.1.parquetmr.txt
templates/include/glean/glean.1.schema.json
validation/glean/metrics.1.all.pass.json

Please note that the new `android_sdk_version` is optional, as this is an Android specific field.

Add the optional `android_sdk_version` to glean pings

---

schemas/glean/baseline/baseline.1.schema.json
schemas/glean/events/events.1.schema.json
schemas/glean/metrics/metrics.1.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json
schemas/org-mozilla-reference-browser/events/events.1.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json
schemas/org-mozilla-samples-glean/events/events.1.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/glean.1.schema.json

This way I can remove this: https://github.com/fbertsch/mozilla-schema-generator/blob/9d27dcc18a31c9c2061282893aeefad4771cedcf/mozilla_schema_generator/glean_ping.py#L33

Add explicit types to Glean pings

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/shield-study-addon/shield-study-addon.3.schema.json
schemas/telemetry/shield-study-error/shield-study-error.3.schema.json
schemas/telemetry/shield-study/shield-study.3.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
templates/include/telemetry/environment.1.schema.json
templates/include/telemetry/mainPayload.1.schema.json
templates/telemetry/shield-study-addon/shield-study-addon.3.schema.json
templates/telemetry/shield-study-error/shield-study-error.3.schema.json
templates/telemetry/shield-study/shield-study.3.schema.json

I used the following script to find all occurrences of `"type": ["array", "object"]`:
```python
#!/usr/bin/env python3
import json
import sys
from collections import deque
def main():
document = json.load(sys.stdin)
search_term = {"object", "array"}
results = []
queue = deque([("root", document)])
while queue:
name, node = queue.popleft()
if not isinstance(node, dict):
continue
dtype = node.get("type")
if dtype and isinstance(dtype, list) and search_term.issubset(set(dtype)):
results.append((name, node))
for key, value in node.items():
queue.append((f"{name}.{key}", value))
results = [x[0] for x in results]
for item in results:
print(item)
if __name__ == "__main__":
main()
```
This is saved as `find-array-object.py`.
This one-liner prints out unique errors (I used some form of this to …

Avoid incompatible array and object union type

---

schemas/telemetry/main/main.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
templates/include/telemetry/mainPayload.1.schema.json
validation/telemetry/main.4.log.fail.json
validation/telemetry/main.4.log_empty.pass.json
validation/telemetry/main.4.log_variable.pass.json

re: https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/291#discussion_r266180942

Add a full schema for payload.logs in main pings

---

schemas/eng-workflow/bmobugs/bmobugs.1.schema.json
templates/eng-workflow/bmobugs/bmobugs.1.schema.json
validation/eng-workflow/bmobugs.1.flags.pass.json
validation/eng-workflow/bmobugs.1.newer.pass.json
validation/eng-workflow/bmobugs.1.oldone.pass.json

Here's the schema for the first version of the BMO Simple ping.
To fit in the eng-workflow namespace the doctype name is 'bmobugs'.
Note the schema has run against all bugs in the BMO database as of a
late-february snapshot. I provided 3 examples that cover most variations.
what's next / what is missing fro this PR, @mreid-moz ?

Add schema and passing examples for BMO simple ping

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/main.4.headless.fail.json
validation/telemetry/main.4.headless.pass.json

Fixes bug 1536175
Might be nice to know if the ping's coming from a headless Firefox.

Add `Headless` to Telemetry Environment.

---

.circleci/config.yml

By deleting schemas directory before generating them we can catch those written by hand without a template.

Improve schema/template inconsistency check

---

schemas/glean/baseline/baseline.1.parquetmr.txt
schemas/glean/baseline/baseline.1.schema.json
schemas/glean/events/events.1.parquetmr.txt
schemas/glean/events/events.1.schema.json
schemas/glean/metrics/metrics.1.parquetmr.txt
schemas/glean/metrics/metrics.1.schema.json
schemas/org-mozilla-fenix/baseline/baseline.1.parquetmr.txt
schemas/org-mozilla-fenix/baseline/baseline.1.schema.json
schemas/org-mozilla-fenix/events/events.1.parquetmr.txt
schemas/org-mozilla-fenix/events/events.1.schema.json
schemas/org-mozilla-fenix/metrics/metrics.1.parquetmr.txt
schemas/org-mozilla-fenix/metrics/metrics.1.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.1.parquetmr.txt
schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json
schemas/org-mozilla-reference-browser/events/events.1.parquetmr.txt
schemas/org-mozilla-reference-browser/events/events.1.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.1.parquetmr.txt
schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.1.parquetmr.txt
schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json
schemas/org-mozilla-samples-glean/events/events.1.parquetmr.txt
schemas/org-mozilla-samples-glean/events/events.1.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.1.parquetmr.txt
schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/glean.1.parquetmr.txt
templates/include/glean/glean.1.schema.json

Use case: custom pings need to be able to be sent without the client_id to preserve privacy.
@fbertsch: Does this require a version bump?

glean: 1529226: Make client_id optional

---

schemas/activity-stream/spocs-fills/spocs-fills.1.schema.json
templates/activity-stream/spocs-fills/spocs-fills.1.schema.json
validation/activity-stream/spocs-fills.1.sample.pass.json

This adds a new schema (`spocs-fills`) to Activity Stream.
The schema was defined in [bug 1535717](https://bugzilla.mozilla.org/show_bug.cgi?id=1535717#c9).
r? @jklukas 
/cc Kirill, Kenny

Bug 1535717 - Add SPOCS fill telemetry for Activity Stream

---

schemas/activity-stream/spocs-fills/spocs-fills.1.schema.json
templates/activity-stream/spocs-fills/spocs-fills.1.schema.json
validation/activity-stream/spocs-fills.1.sample.pass.json

This adds a new enum entry to the `reason` column of the SPOCS Fill in Activity Stream.
r? @jklukas

Add a new enum entry to activity stream spocs fill

---

schemas/mobile/activation/activation.1.schema.json
templates/mobile/activation/activation.1.schema.json
validation/mobile/activation.1.both_ids.fail.json
validation/mobile/activation.1.sample.pass.json

This makes mobile/activation consistent with existing pings (core
and mobile events) that have an integer "tz" field given in minutes.
This is an incompatible change, but since it's a new ping that's not yet deployed, we can simply delete the existing BQ table before merging and let the machinery recreate it.

Integer tz for mobile/activation

---

schemas/glean/baseline/baseline.1.schema.json
schemas/glean/events/events.1.schema.json
schemas/glean/metrics/metrics.1.schema.json
schemas/org-mozilla-fenix/activation/activation.1.schema.json
schemas/org-mozilla-fenix/baseline/baseline.1.schema.json
schemas/org-mozilla-fenix/events/events.1.schema.json
schemas/org-mozilla-fenix/metrics/metrics.1.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json
schemas/org-mozilla-reference-browser/events/events.1.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json
schemas/org-mozilla-samples-glean/events/events.1.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json
schemas/org-mozilla-tv-firefox/baseline/baseline.1.schema.json
schemas/org-mozilla-tv-firefox/events/events.1.schema.json
schemas/org-mozilla-tv-firefox/metrics/metrics.1.schema.json
templates/include/glean/labeled_group.1.schema.json
validation/glean/baseline.1.all.pass.json

Expand the regex pattern for Glean labeled metrics to allow for dotted snakecase.

Glean: allow dotted snake-case for labeled metric labels

---

schemas/eng-workflow/build/build.1.schema.json
templates/eng-workflow/build/build.1.schema.json

This fixes the two `eng-workflow` issues [here](https://gist.github.com/acmiyaguchi/bbfb78590f0c5030c87ade879405d73e). In these cases, defaulting to string is the correct thing to do anyways.

Add missing "string" type.

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
templates/include/telemetry/environment.1.schema.json

Addresses #341. This affects the environment template, and hence many different `docType`s.

Allow null values for environment/addons/theme/updateDay

---

schemas/telemetry/prio/prio.4.schema.json
templates/telemetry/prio/prio.4.schema.json

This fixes the prio `payload.prioData.prio` field so it conforms to an actual object. Currently, it is casted into a string instead of a repeated struct.
I've dropped the table in `shared-nonprod` in preparation for this PR. 

Update prio schema

---

schemas/glean/baseline/baseline.1.schema.json
schemas/glean/events/events.1.schema.json
schemas/glean/metrics/metrics.1.schema.json
schemas/org-mozilla-fenix/activation/activation.1.schema.json
schemas/org-mozilla-fenix/baseline/baseline.1.schema.json
schemas/org-mozilla-fenix/bookmarks_sync/bookmarks_sync.1.schema.json
schemas/org-mozilla-fenix/events/events.1.schema.json
schemas/org-mozilla-fenix/history_sync/history_sync.1.schema.json
schemas/org-mozilla-fenix/metrics/metrics.1.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json
schemas/org-mozilla-reference-browser/events/events.1.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json
schemas/org-mozilla-samples-glean/baseline/baseline.1.schema.json
schemas/org-mozilla-samples-glean/events/events.1.schema.json
schemas/org-mozilla-samples-glean/metrics/metrics.1.schema.json
schemas/org-mozilla-tv-firefox/baseline/baseline.1.schema.json
schemas/org-mozilla-tv-firefox/events/events.1.schema.json
schemas/org-mozilla-tv-firefox/metrics/metrics.1.schema.json
templates/include/glean/labeled_group.1.schema.json
validation/glean/baseline.1.all.pass.json

This is the first part of the fix required to deal with [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1566764).

Enable the use of "dashes" in metric labels for Glean

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/main.4.attribution.pass.json

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1567339)

Bug 1567339 - Add parameters to attribution in environment data

---

schemas/activity-stream/impression-stats/impression-stats.1.schema.json
templates/activity-stream/impression-stats/impression-stats.1.schema.json
validation/activity-stream/impression-stats.1.save-to-pocket.pass.json

r? @jklukas 
Per the offline conversation, we do have some impression stats pings for Activity Stream that do not require `source` as required.
Thanks!

Remove 'source' from the required fields for impression-stats

---

.circleci/config.yml

This should fix empty integration reports occurring due to bad sampled data at the edge.

Update edge validator

---

schemas/telemetry/main/main.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
templates/include/telemetry/mainPayload.1.schema.json

This fixes #363 using the environment information on [this page](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/telemetry/data/main-ping.html). I've also checked the additionalProperties to double check the types of each of the fields. The table in [this issue](https://github.com/mozilla/gcp-ingestion/issues/711#issue-472594034) shows the types and frequency of each field.
I left out `addons` and `flashVersion` because the docs say the fields are obsolete. Based on the data, it seems that they're being reported by a significant number of clients. It might be useful to add here just to increase the coverage of the schema and to reduce the size of additional properties.

Fix #363 - Update `payload.info` in main ping schema

---

schemas/metadata/decoded/decoded.1.schema.json
schemas/metadata/error/error.1.schema.json
templates/include/metadata/additionalProperties.1.schema.json
templates/include/metadata/ingestionTopLevel.1.schema.json
templates/metadata/decoded/decoded.1.schema.json
templates/metadata/error/error.1.schema.json
templates/metadata/structured-ingestion/structured-ingestion.1.schema.json
templates/metadata/telemetry-ingestion/telemetry-ingestion.1.schema.json

We factor out additional_properties, which is not needed for payload_bytes
tables. We also include client_id and docType, etc. where those might be
available in the pipeline.

Fixups to metadata schemas for payload_bytes tables

---

schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
templates/telemetry/first-shutdown/first-shutdown.4.schema.json

This fixes #368 by adding a schema for first shutdown pings. Since this is a copy of the main ping, we should treat it like the main ping during schema generation.

Fix #368 - Add a schema for first-shutdown pings

---

.circleci/config.yml

This updates a small piece of the CI config that was missed during the transition from dev to master. This sets the cache to the latest run for the day and is used during the `restore_cache` step.
---

Update nightly CI job from dev to master

---

schemas/telemetry/new-profile/new-profile.4.schema.json
templates/telemetry/new-profile/new-profile.4.schema.json
validation/telemetry/new-profile.4.sample.pass.json

This explicitely leaves out changes to the parquet schema, as we still
don't have a good way to coerce potentially different data types (numbers, strings, booleans) into a single type.
(Even though for now it's definitely only a string in the new-profile ping)
m-c Patch: https://bugzilla.mozilla.org/show_bug.cgi?id=1570652
This should land first so that we're sure we don't break any data in the pipeline (though everything in the payload is optional already)

Add new scalar data to new-profile ping schema

---

schemas/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.parquetmr.txt
schemas/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.schema.json
templates/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.parquetmr.txt
templates/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.schema.json
validation/firefox-launcher-process/launcher-process-failure.1.sample.pass.json

This patch is to add a new field `is_admin_without_uac` in the existing `launcher-process-failure` ping.
https://bugzilla.mozilla.org/show_bug.cgi?id=1567605

Add is_admin_without_uac to the launcher-process-failure ping

---

schemas/telemetry/voice/voice-feedback.1.schema.json
schemas/telemetry/voice/voice.1.parquetmr.txt
schemas/telemetry/voice/voice.1.schema.json
templates/telemetry/voice/voice-feedback.1.schema.json
templates/telemetry/voice/voice.1.parquetmr.txt
templates/telemetry/voice/voice.1.schema.json
validation/telemetry/voice-feedback.1.normal.pass.json
validation/telemetry/voice.1.full.pass.json
validation/telemetry/voice.1.minimal.pass.json

This is a schema for a custom Telemetry ping for the Firefox Voice project (an extension that receives and handles voice commands).
We talked with @sunahsuh about this, but I'm kind of making it up as I go, so I'm not sure if I've put the schema in the appropriate location, or if there's other things I should include in the PR.
Note this includes PII (the exact voice commands), and it's our understanding that it's OK to store this information in Telemetry (assuming that we've received appropriate consent in-product). We've avoided full URLs, though we have included URL domains.
Note: we're still getting data review on this, and will hold the PR until we've also sent this proposed data through that review.
The actual data:
* We expect to submit one ping per interaction, so this covers …

Add a Telemetry schema for Firefox Voice

---

schemas/telemetry/voice/voice-feedback.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/telemetry/voice/voice-feedback.4.schema.json
templates/telemetry/voice/voice.4.schema.json
validation/telemetry/voice-feedback.4.normal.pass.json
validation/telemetry/voice.4.full.pass.json
validation/telemetry/voice.4.minimal.pass.json

One more change I missed yesterday: the version specified in the schema is still 1 vs 4

Fix schema version specified in voice schema

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/crash.4.null_vendor.pass.json

I noticed this as a common error with a few different ping types (using on @acmiyaguchi 's helpful query over in #400 🎉).

Allow null values for environment.build.vendor

---

schemas/glean/baseline/baseline.1.schema.json
schemas/glean/events/events.1.schema.json
schemas/glean/metrics/metrics.1.schema.json
schemas/org-mozilla-fenix/activation/activation.1.schema.json
schemas/org-mozilla-fenix/baseline/baseline.1.schema.json
schemas/org-mozilla-fenix/bookmarks_sync/bookmarks_sync.1.schema.json
schemas/org-mozilla-fenix/events/events.1.schema.json
schemas/org-mozilla-fenix/history_sync/history_sync.1.schema.json
schemas/org-mozilla-fenix/metrics/metrics.1.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json
schemas/org-mozilla-reference-browser/events/events.1.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json
schemas/org-mozilla-tv-firefox/baseline/baseline.1.schema.json
schemas/org-mozilla-tv-firefox/events/events.1.schema.json
schemas/org-mozilla-tv-firefox/metrics/metrics.1.schema.json
templates/include/glean/glean.1.schema.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1581556 for context and analysis.
Experiment names were being rejected for not being in kebab case, causing all pings for the experiment-enrolled cohort to be rejected.  This just removes the regex from experiment and branch names to avoid this sort of problem in the future.  Unless there are other, unrelated, reasons to restrict experiment names, this might be the best solution.

1531556: Allow any string -- not just snake case -- for experiment names

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json

This will make `environment.system.os.version` available in BigQuery
schemas. Although we're receiving only strings in this field (verified
on AWS on 2019-09-02), its type in the schema was set to union of string
and integer.

Set `environment.system.os.version` type to string

---

schemas/telemetry/sync/sync.4.schema.json
templates/include/telemetry/syncItem.1.schema.json
templates/include/telemetry/syncNamedCount.1.schema.json
validation/telemetry/sync.4.sample.pass.json

This was added in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1552621), with each step having a name, millisecond
duration, and optional named counts. The new bookmarks engine uses
these to report finer-grained stats for each stage.
(I didn't trigger the integration test because I don't have
permission to push to this repo).

Add the `steps` field to the Sync ping

---

schemas/telemetry/core/core.10.schema.json
schemas/telemetry/core/core.2.schema.json
schemas/telemetry/core/core.3.schema.json
schemas/telemetry/core/core.4.schema.json
schemas/telemetry/core/core.5.schema.json
schemas/telemetry/core/core.6.schema.json
schemas/telemetry/core/core.7.schema.json
schemas/telemetry/core/core.8.schema.json
schemas/telemetry/core/core.9.schema.json
templates/include/telemetry/coreCommon.2.schema.json
validation/telemetry/core.10.one_digit_displayversion.pass.json

I noticed there are several validation errors on `core` pings like:
`1558     org.everit.json.schema.ValidationException: #/displayVersion: string [2.0.9] does not match pattern ^[0-9]{2,3}\.`
This relaxes the pattern to start with one or more digits and a dot. 
I'm not sure which application(s) are reporting versions like `2.0.9`, but it seems consistent in that there are many like `2.0.8`, `2.0.7` and so on.

Relax the displayVersion pattern to allow "2.0.1" for example.

---

schemas/telemetry/core/core.10.schema.json
schemas/telemetry/core/core.2.schema.json
schemas/telemetry/core/core.3.schema.json
schemas/telemetry/core/core.4.schema.json
schemas/telemetry/core/core.5.schema.json
schemas/telemetry/core/core.6.schema.json
schemas/telemetry/core/core.7.schema.json
schemas/telemetry/core/core.8.schema.json
schemas/telemetry/core/core.9.schema.json
templates/include/telemetry/coreCommon.2.schema.json
validation/telemetry/core.10.sample.pass.json

Per the Firefox docs[1] and source code[2], the field should
be called "campaignId".
[1] https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/data/core-ping.html
[2] https://searchfox.org/mozilla-central/source/mobile/android/base/java/org/mozilla/gecko/telemetry/pingbuilders/TelemetryCorePingBuilder.java#60
I ran a couple of queries too:
```
select campaign, count(*) from telemetry.core where date(submission_timestamp) = '2019-09-10' group by 1
```
Results were all null.
vs. 
```
select json_extract_scalar(additional_properties, '$.campaignId') as campaign_id, count(*) from telemetry.core where date(submission_timestamp) = '2019-09-10' group by 1
```
Lots of non-null values.

Add "campaignId" field

---

schemas/glean/baseline/baseline.1.schema.json
schemas/glean/events/events.1.schema.json
schemas/glean/metrics/metrics.1.schema.json
schemas/org-mozilla-fenix/activation/activation.1.schema.json
schemas/org-mozilla-fenix/baseline/baseline.1.schema.json
schemas/org-mozilla-fenix/bookmarks_sync/bookmarks_sync.1.schema.json
schemas/org-mozilla-fenix/events/events.1.schema.json
schemas/org-mozilla-fenix/history_sync/history_sync.1.schema.json
schemas/org-mozilla-fenix/metrics/metrics.1.schema.json
schemas/org-mozilla-reference-browser/baseline/baseline.1.schema.json
schemas/org-mozilla-reference-browser/events/events.1.schema.json
schemas/org-mozilla-reference-browser/metrics/metrics.1.schema.json
schemas/org-mozilla-tv-firefox/baseline/baseline.1.schema.json
schemas/org-mozilla-tv-firefox/events/events.1.schema.json
schemas/org-mozilla-tv-firefox/metrics/metrics.1.schema.json
templates/include/glean/timing_distribution.1.schema.json

https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/424 reinstated the unnecessary information in a timing distribution as required.  Therefore, we started seeing newly rejected pings.  This retains those fields, but just makes them not required so they won't be rejected by the schema when missing.

1585019: Remove unnecessary timing_distribution keys as required

---

.circleci/config.yml
.dockerignore
Dockerfile
scripts/assert-consistent-schemas
scripts/assert-telemetry-version

This tackles 1/2 items in issue #413, which includes checking that the version number is set up correctly. The goal of this change is to add a location where more checks can be added.

Add checks for telemetry version number to CI

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json
templates/include/telemetry/mainPayload.1.schema.json
validation/telemetry/main.4.latewrites.fail.json
validation/telemetry/main.4.latewrites.pass.json

This adds some of the missing fields from https://github.com/mozilla/mozilla-schema-generator/issues/47
A couple of things to note - I allowed for nulls in some, but not all, of the boolean fields based on nearby fields, and I couldn't find a real example of lateWrites, so I'm going by what's in the [main ping docs](https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/data/main-ping.html#latewrites).

Add some missing fields to the environment and main payload.

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json

userPrefs will show in the schema with this change as strings if we switch to `--resolve cast`.

Main ping fields

---

schemas/telemetry/sync/sync.5.schema.json
scripts/assert-telemetry-version
templates/telemetry/sync/sync.5.schema.json
validation/telemetry/sync.5.sample.pass.json

This is a copy of v4 schema that will support migration of sync queries
to GCP.

Bug 1572744 - Add schema for v5 of Sync ping

---

schemas/telemetry/voice/voice.4.schema.json
templates/telemetry/voice/voice.4.schema.json
validation/telemetry/voice.4.full.pass.json

Voice bug: https://github.com/mozilla/firefox-voice/issues/546
Adds to ping:
* Date of first installation
* Number of tabs open
* Local time of day (hour)
* Country
* Server timing for DeepSpeech
* Audio recording time
* Performance measure (time) post-processing
~Also removes some fields related to a component (intent parser) that we decided not to implement separately.~

Add new Firefox Voice telemetry fields

---

schemas/telemetry/crash/crash.4.schema.json
templates/telemetry/crash/crash.4.schema.json

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1595904)
This [redash query](https://sql.telemetry.mozilla.org/queries/66131/source) verifies that all fields in the metadata structure are strings. 
Row | key | type | freq |  
-- | -- | -- | -- | --
1 | AsyncShutdownTimeout | string | 644 |  
2 | BlockedDllList | string | 549 |  
3 | BlocklistInitFailed | string | 171 |  
4 | ContainsMemoryReport | string | 1718 |  
5 | CrashTime | string | 14726 |  
6 | EventLoopNestingLevel | string | 1487 |  
7 | IndexedDBShutdownTimeout | string | 21 |  
8 | LowCommitSpaceEvents | string | 2057 |  
9 | MemoryErrorCorrection | string | 10303 |  
10 | MozCrashReason | string | 7293 |  
11 | OOMAllocationSize | string | 4000 |  
12 | RemoteType | string | 7423 |  
13 | ShutdownProgress | string | …

Bug 1595904 - Add missing metadata fields to crash pings from "crash" ping source docs

---

schemas/activity-stream/events/events.1.schema.json
templates/activity-stream/events/events.1.schema.json
validation/activity-stream/events.1.alternative.pass.json

The local tests worked great, only identified a few missing valid values for `page` and `session_id`. Note that the "page" for the Chinese build needs to be added in the future, so expect some validation errors for that.
@jklukas r?

Add more valid values for Activity Stream Events

---

schemas/firefox-installer/install/install.1.parquetmr.txt
schemas/firefox-installer/install/install.1.schema.json
templates/firefox-installer/install/install.1.parquetmr.txt
templates/firefox-installer/install/install.1.schema.json
validation/firefox-installer/install.1.full.pass.json

Add 'silent' to installer ping

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1595586)
In the bug, the documentation was updated to include this field in the graphics subsection. This PR adds the field to be transformed into a BigQuery column.

 Bug 1595586 - Add environment.system.gfx.ContentBackend

---

schemas/telemetry/crash/crash.4.schema.json
templates/telemetry/crash/crash.4.schema.json

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1604913)
Reference: https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/data/crash-ping.html

 Bug 1604913 - Add payload.minidumpSha256Hash to telemetry.crash_v4

---

schemas/telemetry/crash/crash.4.schema.json
templates/telemetry/crash/crash.4.schema.json

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1604666)

Bug 1604666 - Add `payload.crashId` in telemetry.crash_v4

---

schemas/mozza/event/event.1.schema.json
schemas/pocket/fire-tv-events/fire-tv-events.1.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/focus-event/focus-event.1.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/mobile-event/mobile-event.1.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/sync/sync.4.schema.json
schemas/telemetry/sync/sync.5.schema.json
templates/include/common/event.1.schema.json
templates/include/telemetry/mainPayload.1.schema.json

These values should never be negative, but we are seeing a significant number
of negative values since Firefox 71. Since we have not been able to determine
the cause and the current situation is leading us to undercount in all desktop
analyses, we are going to allow negative values to start flowing through.
See bugs
https://bugzilla.mozilla.org/show_bug.cgi?id=1592012#c15
and
https://bugzilla.mozilla.org/show_bug.cgi?id=1602521

Allow negative sessionLengths and event timestamps

---

schemas/activity-stream/events/events.1.schema.json
schemas/activity-stream/impression-stats/impression-stats.1.schema.json
schemas/activity-stream/sessions/sessions.1.schema.json
templates/activity-stream/events/events.1.schema.json
templates/activity-stream/impression-stats/impression-stats.1.schema.json
templates/activity-stream/sessions/sessions.1.schema.json
templates/activity-stream/spoc-fills/spoc-fills.1.schema.json
templates/include/activity-stream/impressionId.1.schema.json
templates/include/activity-stream/page.1.schema.json
templates/include/activity-stream/sessionId.1.schema.json
validation/activity-stream/sessions.1.sample.pass.json

r? @jklukas 
This migrates the table `Tiles.assa_sessions_daily_by_client_id` to BQ.
Schema updates:
* Remove the `is_prerendered` and `client_region`
* Type change from "double" to "integer" for `load_trigger_ts`, `visibility_event_rcvd_ts`, and `topsites_first_painted_ts`
~~Looks the like there is a test bustage in `mozilla-pipeline-schemas-hindsight`, still investigating if it relates to this change.~~
[Update 1]: test failure is now fixed.

Bug 1607315 - Add Activity Stream session ping

---

schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/glean.1.schema.json

It's already in the submission URL and thus just data duplication.
It needs to stay optional, so that old pings are still valid against the
same version of the schema.

Bug 1609149 Make the `ping_type` optional for Glean pings

---

schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/glean.1.schema.json

1609218: Add ping reason field in ping_info

---

README.md

As suggested in https://github.com/mozilla-services/mozilla-pipeline-schemas/issues/431#issuecomment-575565962

Update docs to remove `dev` branch references and reflect GCP releases

---

schemas/telemetry/sync/sync.4.schema.json
schemas/telemetry/sync/sync.5.schema.json
templates/include/telemetry/syncPayload.1.schema.json
validation/telemetry/sync.4.null_device_version.pass.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1611168
We already allow device `os` to be null, but we also need to allow
null `version`.

Bug 1611168 Allow null device version in sync pings

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/main.4.attribution.pass.json

r?@acmiyaguchi Similar to #357 but for `ua` added in https://bugzilla.mozilla.org/show_bug.cgi?id=1595063
https://firefox-source-docs.mozilla.org/toolkit/components/telemetry/data/environment.html

Bug 1595063 - Add ua attribution to environment data

---

schemas/metadata/error/error.1.schema.json
schemas/metadata/raw/raw.1.schema.json
templates/include/metadata/raw.1.schema.json
templates/metadata/error/error.1.schema.json
templates/metadata/raw/raw.1.schema.json

In particular, we draw attention to the fact that IP address fields
in error tables will always be null.

Bug 1613225 Add descriptions to payload_bytes_* fields

---

schemas/telemetry/sync/sync.4.schema.json
schemas/telemetry/sync/sync.5.schema.json
templates/include/telemetry/syncItem.1.schema.json
validation/telemetry/sync.4.null_device_version.pass.json

This issue is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1614418 and was previously reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1611168
There was already a PR trying to fix this issue a while ago: https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/490
However, I believe the previous PR didn't address the right part of the schema to be changed.
If the fix here looks right, I guess also the validation tests introduced in https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/490 should be changed?

Bug 1614418 allow null for syncs device versions

---

schemas/default-browser-agent/default-browser/default-browser.1.schema.json
templates/default-browser-agent/default-browser/default-browser.1.schema.json
validation/default-browser-agent/default-browser/default-browser.1.pass.json

See the bug [https://bugzilla.mozilla.org/show_bug.cgi?id=1602463] for the details.

Bug 1602463 - Add a schema for the new default-browser ping

---

.dockerignore
.gitignore

This fixes #505. It prefixes the path for `build` in the `.gitignore` with a forward slash to denote to ignore only at the root of the repository.

Fix #505 - Ignore only build at root directory; add java ignores

---

schemas/telemetry/voice-feedback/voice-feedback.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/telemetry/voice-feedback/voice-feedback.4.schema.json
templates/telemetry/voice/voice.4.schema.json
validation/telemetry/voice-feedback.4.normal.pass.json
validation/telemetry/voice.4.full.pass.json

- Copy of utterance in the feedback, for users that haven't opted in to utterance recording
- Whether a user has enabled a wakeword
- If a user started Voice with a wakeword, and what wakeword
- The timestamp of opt-in for utterance storage
- Whether the user opted in to audio recording
Upstream bugs:
- https://github.com/mozilla/firefox-voice/issues/574
- https://github.com/mozilla/firefox-voice/issues/945
- https://github.com/mozilla/firefox-voice/issues/587
- https://github.com/mozilla/firefox-voice/issues/588

Add new fields for Firefox Voice:

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
scripts/extract_probe_dictionary_descriptions
templates/include/telemetry/environment.1.schema.json

I wrote a small script to extract descriptions from [probe-dictionary](https://github.com/mozilla/probe-dictionary/blob/master/environment.json) and add them to corresponding fields that were missing the description. 

Bug 1603536 Add descriptions for environment from probe dictionary

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json
templates/telemetry/new-profile/new-profile.4.schema.json
templates/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
validation/telemetry/event.4.sample.pass.json

Add missing column `environment.system.gfx.adapters.adapterDriver` to environment and add missing types to schemas.
Fixes part of https://bugzilla.mozilla.org/show_bug.cgi?id=1614416

Add missing environement column and types

---

schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
templates/telemetry/third-party-modules/third-party-modules.4.schema.json
validation/telemetry/third-party-modules.4.moduleindex.fail.json
validation/telemetry/third-party-modules.4.sample.pass.json
validation/telemetry/third-party-modules.4.stackframe.fail.json
validation/telemetry/third-party-modules.4.trustflags.fail.json
validation/telemetry/third-party-modules.4.unknownmodule.pass.json

This patch adds a new optional field `isDependent` in the existing
third-party-module ping.
https://bugzilla.mozilla.org/show_bug.cgi?id=1620118

Bug 1620118 - Add the isDependent field to the third-party-modules ping

---

.github/pull_request_template.md
README.md

Notably, no need to ask people to run the integration tests
manually since we now do this automatically. The instructions
were out of date and hard to follow so I just removed them, if
people really care to do this themselves they can always look at the
circle configuration.

Update docs and pull request template

---

schemas/firefox-accounts/activity-flow-metrics/activity-flow-metrics.1.schema.json
schemas/firefox-accounts/amplitude-event/amplitude-event.1.schema.json
templates/firefox-accounts/activity-flow-metrics/activity-flow-metrics.1.schema.json
templates/firefox-accounts/amplitude-event/amplitude-event.1.schema.json
validation/firefox-accounts/activity-flow-metrics.1.sample.pass.json
validation/firefox-accounts/amplitude-event.1.fxa-auth-server--fxa_login--success.pass.json
validation/firefox-accounts/amplitude-event.1.fxa-content-server--fxa_reg--view.pass.json
validation/firefox-accounts/amplitude-event.1.fxa-payments-server--fxa_pay_setup--engage.pass.json
validation/firefox-accounts/amplitude-event.1.sample.pass.json

Opening early for feedback from @jklukas. Many optional fields to be added later. Things I'm particularly curious about:
* Should the parsed `uri` fields (`document_namespace` and so on) be grouped under a separate `metadata` property, as in the `metadata` schema templates?
* Should the `document_version` be specified, as I've done here, or left as just generic string type?
* Should I extract repeated fields into a template file, and/or borrow common fields (say, the UUID regex) from some common location?
Fixes https://github.com/mozilla/fxa/issues/4456.
-----

Add initial Firefox Accounts metrics event schemas and templates

---

schemas/telemetry/crash/crash.4.schema.json
templates/include/telemetry/hexAddress.1.schema.json
templates/telemetry/crash/crash.4.schema.json
validation/telemetry/crash.4.null_stackTraces.pass.json
validation/telemetry/crash.4.stackTraces.pass.json

Bug 1623626 - Add crash stacks to crash schema

---

schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/glean.1.schema.json

These are less clear-cut on non-mobile.
More specific hardware identification might be necessary for Desktop use cases.

Bug 1625207 - Make device manufacturer and model optional

---

schemas/telemetry/crash/crash.4.schema.json
templates/telemetry/crash/crash.4.schema.json

Bug 1624986 - Fix specification of sessionId, crashTime fields in crash schema

---

schemas/telemetry/sync/sync.4.schema.json
schemas/telemetry/sync/sync.5.schema.json
templates/include/telemetry/syncPayload.1.schema.json
validation/telemetry/sync.4.null_device_version.pass.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1625547
The default device ID for sync payloads is `00000000000000000000000000000000` and is currently not supported in the schema. This PR adds support for this default device ID.

[Bug 1625547] Sync payload allow default device ID (00000000000000000000000000000000)

---

scripts/bigquery_schema_diff.py

This fixes broken CI on master, which is caused by the `bigquery_schema_diff` being run for the same revision in the base and head references. This also adds an option to the script to specify a separate directory to run tests in via the `--root-directory` option.

Allow running bigquery_schema_diff for same base and head refs

---

schemas/telemetry/core/core.10.schema.json
schemas/telemetry/core/core.2.schema.json
schemas/telemetry/core/core.3.schema.json
schemas/telemetry/core/core.4.schema.json
schemas/telemetry/core/core.5.schema.json
schemas/telemetry/core/core.6.schema.json
schemas/telemetry/core/core.7.schema.json
schemas/telemetry/core/core.8.schema.json
schemas/telemetry/core/core.9.schema.json
templates/include/telemetry/coreCommon.2.schema.json
validation/telemetry/core.10.sample.pass.json

Bug 1627843 - Missing iOS Core ping fields

---

.circleci/config.yml

This should fix #534 by removing the branch filter in the circleci configuration.

Fix #534 - Always run test step in circleci

---

schemas/telemetry/installation/installation.1.schema.json
templates/telemetry/installation/installation.1.schema.json
validation/telemetry/installation.1.sample.pass.json

Bug 1635152 - Fennec Installation ping

---

schemas/telemetry/crash/crash.4.schema.json
templates/telemetry/crash/crash.4.schema.json

This also makes the schema slightly more strict to make sure that
we're actually seeing what we expect to see.

Bug 1635212 - Handle frames property of threads in crash pings

---

schemas/telemetry/installation/installation.1.schema.json
templates/telemetry/installation/installation.1.schema.json
validation/telemetry/installation.1.sample.pass.json

Add v to installation ping

---

schemas/telemetry/crash/crash.4.schema.json
scripts/extract_crash_annotation_fields
templates/telemetry/crash/crash.4.schema.json

Also add a small script, extract_crash_annotation_fields for
automatically grabbing this type of information in the future.

Bug 1631506 - Add some more fields from crash annotations

---

schemas/telemetry/sync/sync.4.schema.json
schemas/telemetry/sync/sync.5.schema.json
templates/include/telemetry/syncPayload.1.schema.json
validation/telemetry/sync.4.null_device_version.pass.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1629695

[Bug 1629695] Add missing sync ping payload.os fields

---

schemas/metadata/decoded/decoded.1.schema.json
schemas/metadata/error/error.1.schema.json
schemas/metadata/pioneer-ingestion/pioneer-ingestion.1.schema.json
schemas/metadata/structured-ingestion/structured-ingestion.1.schema.json
schemas/metadata/telemetry-ingestion/telemetry-ingestion.1.schema.json
templates/include/metadata/ingestionCommonMetadata.1.schema.json
templates/metadata/error/error.1.schema.json

This adds ISP information to the metadata as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1505491 and https://github.com/mozilla/gcp-ingestion/pull/1117.

Bug 1505491 Add ISP information to metadata

---

schemas/telemetry/sync/sync.4.schema.json
schemas/telemetry/sync/sync.5.schema.json
templates/include/telemetry/syncItem.1.schema.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1640713
Defining the outgoing field type as both array and object, it seems like the jsonschema-transpiler removed that field when generating the BQ schema.

[Bug 1640713] Fix sync engines.outgoing field type

---

schemas/default-browser-agent/default-browser/default-browser.1.schema.json
templates/default-browser-agent/default-browser/default-browser.1.schema.json
validation/default-browser-agent/default-browser.1.sample_all_fields.pass.json

[Bug 1621703](https://bugzilla.mozilla.org/show_bug.cgi?id=1621703#c10)
Originally, we planned to have a client id in the default browser agent's ping. However, we eventually decided not to include it. We never merged the code that added the client id, so no pings have ever been sent with this field.

Document default browser agent's client id field as deprecated

---

Dockerfile

We're seeing all test runs currently fail (see [example failure](https://app.circleci.com/pipelines/github/mozilla-services/mozilla-pipeline-schemas/1666/workflows/2af886d5-3764-4da0-9d51-bab9ff994611/jobs/3706/steps)).
This looks to be due to "diff" not being available in the centos8 image
published last week.

Pin Centos image

---

schemas/telemetry/normandy-login-study/normandy-login-study.4.schema.json
templates/telemetry/normandy-login-study/normandy-login-study.4.schema.json
validation/telemetry/normandy-login-study.4.sample.pass.json

This is the schema for a custom addon-based ping that will be coming from a normandy-installed addon. 
A few things I'm unsure on:
1. was `telemetry` the right namespace here?
2. In addition to this, do I need to open any PRs on bigquery ETL if I want the data to end up in a table?
3. this is my first time opening a PR in this repo. tests are passing but I still may have done something wrong
CC
Further reading:
https://bugzilla.mozilla.org/show_bug.cgi?id=1643383
https://bugzilla.mozilla.org/show_bug.cgi?id=1646821
https://experimenter.services.mozilla.com/experiments/google-login-cookie-check/

Add Schema for Custom Ping (Normandy login study Bug 1643383)

---

schemas/firefox-accounts/account-ecosystem/account-ecosystem.1.schema.json
schemas/telemetry/account-ecosystem/account-ecosystem.4.schema.json
templates/firefox-accounts/account-ecosystem/account-ecosystem.1.schema.json
templates/telemetry/account-ecosystem/account-ecosystem.4.schema.json

See discussion in
https://github.com/mozilla/gcp-ingestion/pull/1304#discussion_r443312441

Make ecosystem_device_id an optional field

---

schemas/firefox-accounts/account-ecosystem/account-ecosystem.1.schema.json
schemas/telemetry/account-ecosystem/account-ecosystem.4.schema.json
templates/firefox-accounts/account-ecosystem/account-ecosystem.1.schema.json
templates/telemetry/account-ecosystem/account-ecosystem.4.schema.json

This is a schema-incompatible change. These tables are still being used only
for early stage testing of AET, so it is entirely reasonable to throw away
existing data and recreate them entirely.

Remove ecosystem_device_id fields

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/third-party-modules.4.sample.pass.json

These correspond to telemetry added in
https://bugzilla.mozilla.org/show_bug.cgi?id=1649215
and https://bugzilla.mozilla.org/show_bug.cgi?id=1648304

Add 'openglCompositing' and 'wrCompositor' to schema

---

schemas/telemetry/crash/crash.4.schema.json
templates/telemetry/crash/crash.4.schema.json

Bug 1652777 - Add experimental features to crash ping schema

---

scripts/extract_crash_annotation_fields

Avoids a scary warning when run
(none applicable to this one)

Specify yaml loader in extract_crash_annotation_fields script

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/crash.4.sample.pass.json
validation/telemetry/testpilot.4.sample.pass.json

Bug 1652842 - Add a blocklist field so the environment schema works with pre- and post-bug-1647225 data

---

schemas/telemetry/xfocsp-error-report/xfocsp-error-report.4.schema.json
schemas/xfocsp-error-report/xfocsp-error-report/xfocsp-error-report.4.schema.json
templates/telemetry/xfocsp-error-report/xfocsp-error-report.4.schema.json
templates/xfocsp-error-report/xfocsp-error-report/xfocsp-error-report.4.schema.json
tests/test_duplicate_schemas.py
validation/telemetry/xfocsp-error-report.4.sample.pass.json

Closes #570
This pulls in the commit from that PR and duplicates it in a new namespace.
We will be rerouting these pings in the pipeline so that they can have
stricter access controls.
There is a test case added here so that CI will fail if these two schemas
get out of sync.

Add xfocsp-error-report schema

---

schemas/telemetry/xfocsp-error-report/xfocsp-error-report.4.schema.json
schemas/xfocsp-error-report/xfocsp-error-report/xfocsp-error-report.4.schema.json
templates/telemetry/xfocsp-error-report/xfocsp-error-report.4.schema.json
templates/xfocsp-error-report/xfocsp-error-report/xfocsp-error-report.4.schema.json
validation/telemetry/xfocsp-error-report.4.sample.pass.json

In testing, we found several top-level fields included in the validation
document were going to additional_properties. We add them here.
Of note, we do not add client_id or environment, which are part of the common
ping format but specifically excluded here for user privacy.
Reverts https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/582

Add common ping fields to xfocsp-error-report

---

.github/pull_request_template.md
schemas/metadata/decoded/decoded.1.schema.json
schemas/metadata/error/error.1.schema.json
schemas/metadata/pioneer-decoded/pioneer-decoded.1.schema.json
schemas/metadata/pioneer-error/pioneer-error.1.schema.json
schemas/metadata/pioneer-ingestion/pioneer-ingestion.1.schema.json
schemas/metadata/raw/raw.1.schema.json
schemas/metadata/structured-ingestion/structured-ingestion.1.schema.json
schemas/metadata/telemetry-ingestion/telemetry-ingestion.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/metadata/ingestionCommonMetadata.1.schema.json
templates/include/metadata/raw.1.schema.json

Also see pipeline support in https://github.com/mozilla/gcp-ingestion/pull/1328

Bug 1655477 Support X-Source-Tags header

---

schemas/telemetry/sync/sync.4.schema.json
schemas/telemetry/sync/sync.5.schema.json
templates/include/telemetry/syncItem.1.schema.json
validation/telemetry/sync.4.sample.pass.json

Firefox for iOS is sending `"...outgoing":[{"failed":0,"sent":3}],..."`

[Bug 1659517] #/payload/syncs/0/engines/1/outgoing/0/failed set minimum to 0

---

schemas/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.schema.json
templates/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.schema.json
validation/firefox-launcher-process/launcher-process-failure.1.sample.pass.json

This patch adds a new optional string field `process_type` in the existing
launcher process failure ping.

Bug 1630444 - Add process_type to the launcher process failure ping

---

schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/untrustedModules/untrustedModules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json

The new "account-ecosystem" telemetry ping includes a minimal environment with only a subset of the fields included in most pings following the common ping format. The existing logic in mozilla-schema-generator injects some fields we don't want into the environment, and it's unclear to me why these don't exist in the json schemas directly. There is some discussion of the preference for defining the fields in the raw json schemas (see https://bugzilla.mozilla.org/show_bug.cgi?id=1614416#c3).
If we are able to add the fields at this level, then we can simplify the logic in mozilla-schema-generator as part of https://github.com/mozilla/mozilla-schema-generator/pull/140.
By merging this, we would be adding hasPrefetch to a few tables that currently do _not_ have it. This should be the set of …

Add hasPrefetch and hasSuperfetch

---

schemas/telemetry/account-ecosystem/account-ecosystem.4.schema.json
templates/telemetry/account-ecosystem/account-ecosystem.4.schema.json
validation/telemetry/account-ecosystem.4.sample.pass.json

Currently, the only probes saved into the "account-ecosystem" metrics store
are in process main, so this PR only adds "parent" placeholders for now.
Injection is happening in https://github.com/mozilla/mozilla-schema-generator/pull/140

Bug 1659750 Prepare account-ecosystem ping for probe injection

---

schemas/metadata/metaschema/metaschema.1.schema.json
schemas/pioneer-debug/debug/debug.1.schema.json
schemas/pioneer-debug/deletion-request/deletion-request.1.schema.json
templates/metadata/metaschema/metaschema.1.schema.json
templates/pioneer-debug/defaults.schema.json
tests/test_metadata_defaults.py
tests/test_pipeline_metadata.py
tests/test_telemetry_version.py

This should bring parity with the [regex logic on filepaths in m-s-g](https://github.com/mozilla/mozilla-schema-generator/blob/0bdc35a407b991c3cf6de591a4afee6a8d8ea61a/bin/schema_generator.sh#L76-L91) Once this and https://github.com/mozilla/mozilla-schema-generator/pull/139 are merged, it should be possible to update m-s-g's metadata_merge to look up the appropriate metadata schema based on bq_metadata_format and remove the regex logic.

Introduce "pioneer" value for bq_metadata_format

---

schemas/metadata/metaschema/metaschema.1.schema.json
templates/metadata/metaschema/metaschema.1.schema.json

`bq_metadata_format` actually affects schema generation behavior as of https://github.com/mozilla/mozilla-schema-generator/pull/141

Mark bq_metadata_format as implemented

---

schemas/firefox-accounts/account-ecosystem/account-ecosystem.1.schema.json
schemas/metadata/metaschema/metaschema.1.schema.json
schemas/telemetry/account-ecosystem/account-ecosystem.4.schema.json
templates/firefox-accounts/account-ecosystem/account-ecosystem.1.schema.json
templates/metadata/metaschema/metaschema.1.schema.json
templates/telemetry/account-ecosystem/account-ecosystem.4.schema.json

This moves us from using an informal ad hoc format for specifying paths to
a proposed IETF standard.
I came across this standard as I was starting to draft a PR for relying on
jwe_mappings in the AET decoder. In particular, the Jackson library provides
an implementation of JSON Pointer that simplifies the AET logic.
See draft: https://github.com/mozilla/gcp-ingestion/pull/1374

Require JSON Pointer format for jwe_mappings

---

schemas/activity-stream/on-save-recs/on-save-recs.1.schema.json
templates/activity-stream/on-save-recs/on-save-recs.1.schema.json
validation/activity-stream/on-save-recs.1.sample.pass.json

This creates a new telemetry ping to track impressions, clicks, and saves of on-save recommendations shown to users when they save a webpage via the Pocket button in the address bar.
I have included most standard information that we track on AS pings and entered this ping into the `activity-stream` namespace, as per guidance from @ncloudioj . This ping does not have the FX `client_id`, but instead uses the Pocket `impression_id` as a user identifier.
The only new parameters of note are:
-`model` = name of the machine learning model that generated these recommendations

Bug 1658787 - Add Pocket on-save recs ping

---

schemas/activity-stream/on-save-recs/on-save-recs.1.schema.json
schemas/firefox-accounts/account-ecosystem/account-ecosystem.1.schema.json
templates/firefox-accounts/account-ecosystem/account-ecosystem.1.schema.json

Added to ingestion in https://github.com/mozilla/gcp-ingestion/pull/1404

Bug 1653654 Add oauth_client_id to firefox-accounts AET schema

---

schemas/activity-stream/on-save-recs/on-save-recs.1.schema.json
templates/activity-stream/on-save-recs/on-save-recs.1.schema.json
validation/activity-stream/on-save-recs.1.sample.pass.json

It turns out the data pipeline adds region information based on IP address to all events by default, so no need for the `region` parameter I had added to this ping [earlier](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/608).

Bug 1658787 - Drop region field from on-sav-recs ping

---

schemas/activity-stream/on-save-recs/on-save-recs.1.schema.json
templates/activity-stream/on-save-recs/on-save-recs.1.schema.json
validation/activity-stream/on-save-recs.1.sample.pass.json

Scott and I figured out that the `addon_version` field is irrelevant to this new ping (it was carried over from some Activity Stream pings), so no need for the `addon_version` parameter I had added to this ping [earlier](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/608).

Bug 1658787 - Drop addon_version field from on-save-recs ping

---

schemas/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.schema.json
templates/firefox-launcher-process/launcher-process-failure/launcher-process-failure.1.schema.json
validation/firefox-launcher-process/launcher-process-failure.1.sample.pass.json

This patch adds a new optional string field `detour_orig_bytes` in the existing
launcher process failure ping.

Bug 1588245 - Add detour_orig_bytes to the launcher process failure ping

---

mozilla_pipeline_schemas/cli/bigquery.py
setup.py
tests/test_mps_cli_bigquery.py

This adds a `mps bigquery columns` command, which is intended to be used to make schema diffs a bit easier to read.
```bash
$ pip install .
$ git checkout generated-schemas
$ mps bigquery columns schemas/org-mozilla-reference-browser/baseline/baseline.1.bq 
root.additional_properties STRING
root.client_info.android_sdk_version STRING
root.client_info.app_build STRING
root.client_info.app_channel STRING
root.client_info.app_display_version STRING
root.client_info.architecture STRING
root.client_info.client_id STRING
root.client_info.device_manufacturer STRING
root.client_info.device_model STRING
root.client_info.first_run_date STRING
root.client_info.locale STRING
root.client_info.os STRING
root.client_info.os_version STRING
root.client_info.telemetry_sdk_build STRING
root.document_id …
```

Add command for generating compact set of columns

---

.circleci/config.yml
.circleci/post-artifact.js

This addresses failing nightly jobs that have occurred over the last few months since AWS buckets were deleted.  See #625

Remove edge-validator from CI

---

schemas/telemetry/uninstall/uninstall.4.schema.json

I think this is a weird ordering problem where the tests succeeded on
https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/629
but after merging, it was out of date with the new fissionEnabled field.

Add fissionEnabled to new uninstall ping

---

schemas/pioneer-citp-news-disinfo/measurements/measurements.1.schema.json
templates/pioneer-citp-news-disinfo/measurements/measurements.1.schema.json
validation/pioneer-citp-news-disinfo/measurements.1.sample.pass.json

Main changes are two new fields added to the schema (also removed overly-aggressive validation).

Updates for CITP Pioneer study schema

---

schemas/metadata/metaschema/metaschema.1.schema.json
templates/metadata/metaschema/metaschema.1.schema.json

`delete_after_days` is now used as source of truth for retention policies
in the ops logic per https://bugzilla.mozilla.org/show_bug.cgi?id=1674884

Bug 1674884 Remove NOT YET IMPLEMENTED for delete_after_days

---

schemas/activity-stream/on-save-recs/on-save-recs.1.schema.json
schemas/activity-stream/pocket-button/pocket-button.1.schema.json
templates/activity-stream/on-save-recs/on-save-recs.1.schema.json
templates/activity-stream/pocket-button/pocket-button.1.schema.json
validation/activity-stream/pocket-button.1.door_hanger_click.pass.json
validation/activity-stream/pocket-button.1.on_save_rec_click.pass.json
validation/activity-stream/pocket-button.1.on_save_rec_save.pass.json
validation/activity-stream/pocket-button.1.pocket_button_click.pass.json
validation/activity-stream/pocket-button.1.pocket_button_remove.pass.json
validation/activity-stream/pocket-button.1.pocket_button_unpin.pass.json
validation/activity-stream/pocket-button.1.sample.pass.json

This PR updates a ping introduced in an earlier [PR](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/608) and generalizes it to track all types of interactions with the Pocket button in the nav bar. This ping does not have the FX client_id, but instead uses the Pocket impression_id as a user identifier.
The possible events it can be used to track, as well as test events that I've included:
- [impressions](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/638/files#diff-f8b701b9cdee099f01bfb9798ef670e013a8ab9bd5fa47d55ac7e339675116d7) of on-save recommendations
- [clicks](https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/638/files#diff-7a72508d2dbb9e53f6025e0645f87a4ee5473c07916860fb4fa58018e475dbcc …

Bug 1672763 - Add pocket-button ping.

---

.github/pull_request_template.md

This came up again in a recent PR, and I feel like it might be worth calling out, since adding descriptions to new fields will help us generate comprehensible views in BigQuery. @jklukas any thoughts?

Encourage people to add a descriptions by adding to checklist

---

schemas/telemetry/bhr/bhr.4.schema.json
templates/telemetry/bhr/bhr.4.schema.json
validation/telemetry/bhr.4.sample.pass.json

Bug 1675103 - Define the bhr ping schema.

---

Dockerfile
README.md
mozilla_pipeline_schemas/cli/bigquery.py
mozilla_pipeline_schemas/sink.py
scripts/download-java-dependencies
scripts/mps-shell
tests/conftest.py
tests/test_mps_cli_bigquery.py
tests/test_mps_sink.py
tests/utils.py

This uses ingestion-sink to transform a validation document into a document that can be inserted into a BigQuery table.
This can be used in a few ways. 
```bash
python -m mozilla_pipeline_schemas.sink validation/pioneer-citp-news-disinfo/measurements.1.sample.pass.json | jq
python -m mozilla_pipeline_schemas.sink validation/telemetry/main.4.sample.pass.json | jq '.additional_properties | fromjson'
```
This will probably the base of more sophisticated testing for schema coverage i.e. [bug 1450290](https://bugzilla.mozilla.org/show_bug.cgi?id=1450290). An uber jar containing the class definition `com.mozilla.telemetry.ingestion.sink.config.SinkConfig` should be in the `CLASSPATH`. 

Add ingestion sink transforms via jnius

---

schemas/pioneer-core/demographic-survey/demographic-survey.1.schema.json
templates/pioneer-core/demographic-survey/demographic-survey.1.schema.json
validation/pioneer-core/demographic-survey.1.full.pass.json
validation/pioneer-core/demographic-survey.1.partial.fail.json
validation/pioneer-core/demographic-survey.1.partial.pass.json

This adds the schema for allowing the Rally Core Add-on to send demographic pings. See mozilla-ion/ion-core-addon#182 (data review is [here](https://github.com/mozilla-ion/ion-core-addon/pull/139#issuecomment-736024232)).
Note that all of the sections and the fields are optional.

Add a schema for the Ion/Rally demographics ping

---

schemas/messaging-system/infobar/infobar.1.schema.json
templates/messaging-system/infobar/infobar.1.schema.json
validation/messaging-system/infobar.1.event.pass.json

r? @jklukas
The traffic volume for this ping type is estimated to be similar to `messaging_system.onboarding`.
Strangely, the local tests failed to run,`./scripts/mps-test` hung with the following logging:
```
====================================================================== test session starts ======================================================================
platform linux -- Python 3.6.8, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: /app
plugins: xdist-2.1.0, forked-1.3.0
collecting 0 items  
```

Bug 1687027 - Add a schema for InfoBar of Messaging System

---

schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
templates/telemetry/third-party-modules/third-party-modules.4.schema.json
validation/telemetry/third-party-modules.4.sample.pass.json

This patch adds a new optional integer field `loadStatus`
in the existing third-party-modules ping.

Bug 1686229 - Add loadStatus to the third-party-modules ping

---

schemas/messaging-system/snippets/snippets.1.schema.json
schemas/messaging-system/whats-new-panel/whats-new-panel.1.schema.json
templates/messaging-system/snippets/snippets.1.schema.json
templates/messaging-system/whats-new-panel/whats-new-panel.1.schema.json
validation/messaging-system/snippets.1.source.fail.json
validation/messaging-system/snippets.1.source.pass.json
validation/messaging-system/whats-new-panel.1.browser_session_id.pass.json

This adds two missing fields to the Messaging System schema as described in this [comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1682364#c5).

Bug 1682364 - Add missing fields to Messaging System schema

---

schemas/pioneer-citp-news-disinfo/measurements/measurements.1.schema.json
templates/pioneer-citp-news-disinfo/measurements/measurements.1.schema.json

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1689758)
It's likely that this gets extended by another 90 days within the next few days, but I rather set this policy now to ensure that something like [bug 1690126](https://bugzilla.mozilla.org/show_bug.cgi?id=1690126) doesn't creep up on us again. It was oversight on my part that we didn't have this policy set up on study launch. 
cc @akohlbre 

Bug 1689758 - Set citp-news-disinfo study table to 90 day expiration

---

schemas/pioneer-citp-news-disinfo/measurements/measurements.1.schema.json
templates/pioneer-citp-news-disinfo/measurements/measurements.1.schema.json

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1690637)

Bug 1690637 - Set citp-new-disinfo table retention to 180 days

---

schemas/pioneer-core/demographic-survey/demographic-survey.1.schema.json
templates/pioneer-core/demographic-survey/demographic-survey.1.schema.json
validation/pioneer-core/demographic-survey.1.origin.pass.json

The field is renamed from `hispanicLatinoSpanish` to `hispanicLatinxSpanish`.

Rename the `hispanicLatinoSpanish` field in Rally pings

---

schemas/contextual-services/topsites-click/topsites-click.1.schema.json
schemas/contextual-services/topsites-impression/topsites-impression.1.schema.json
templates/contextual-services/topsites-click/topsites-click.1.schema.json
templates/contextual-services/topsites-impression/topsites-impression.1.schema.json
validation/contextual-services/topsites-click.1.event.pass.json
validation/contextual-services/topsites-impression.1.event.pass.json

This is a follow up for #656 
r? @sunahsuh @BenWu

Bug 1688698 - Add 'source' to TopSites schemas in Contextual Services

---

schemas/telemetry/bhr/bhr.4.schema.json
schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/uninstall/uninstall.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json

[Bug 1694254] Add environment.settings.attribution.dltoken field

---

schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/rate.1.schema.json
validation/glean/glean.1.baseline.pass.json
validation/glean/glean.1.invalid_use_counter.fail.json
validation/glean/glean.1.metrics.pass.json

Technically this is a backward-incompatible change.  However, there is nothing in the wild sending a `rate` metric type yet, so I believe this is ok (and should be even when we get to the schema generator part of this).  But please check my assumption, @frank and @acmiyaguchi .

Fix #660: Add the rate metric type

---

schemas/pioneer-core/uninstall-deletion/uninstall-deletion.1.schema.json
templates/pioneer-core/uninstall-deletion/uninstall-deletion.1.schema.json
validation/pioneer-core/uninstall-deletion.1.full.pass.json

[bug link](https://bugzilla.mozilla.org/show_bug.cgi?id=1696074). This is needed by https://github.com/mozilla-services/data-sandbox-terraform/pull/44 for testing.

Bug 1696074 - Add schema for uninstall-deletion ping in pioneer-core

---

schemas/telemetry/bhr/bhr.4.schema.json
schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/uninstall/uninstall.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/event.4.sample.pass.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1709182
The field was added in https://hg.mozilla.org/mozilla-central/rev/eb40719c0827ea6c5a06bcf497bedc2a7df9d7be

[Bug 1709182] Add environment.settings.update.background column in ping table schemas

---

schemas/telemetry/crash/crash.4.schema.json
templates/telemetry/crash/crash.4.schema.json

GPUProcessLaunchCount and ProfilerChildShutdownPhase were added to
crash pings in https://bugzilla.mozilla.org/show_bug.cgi?id=1710448
and https://bugzilla.mozilla.org/show_bug.cgi?id=1704680, need to
update schemas to match

Add some missing crash annotations

---

schemas/pioneer-core/demographic-survey/demographic-survey.1.schema.json
templates/pioneer-core/demographic-survey/demographic-survey.1.schema.json
validation/pioneer-core/demographic-survey.1.deprecated-income-range.pass.json
validation/pioneer-core/demographic-survey.1.full.pass.json

This deprecates the `income` field of `templates/pioneer-core/demographic-survey/demographic-survey.1.schema.json` in favor of a new field,`exactIncome`. Additionally, it adds `other_asian` as an option to the `race` entry.

Rally: update the demographic survey schema to take the new `exactIncome` field

---

schemas/metadata/decoded/decoded.1.schema.json
schemas/metadata/error/error.1.schema.json
schemas/metadata/pioneer-decoded/pioneer-decoded.1.schema.json
schemas/metadata/pioneer-error/pioneer-error.1.schema.json
schemas/metadata/pioneer-ingestion/pioneer-ingestion.1.schema.json
schemas/metadata/raw/raw.1.schema.json
schemas/metadata/structured-ingestion/structured-ingestion.1.schema.json
schemas/metadata/telemetry-ingestion/telemetry-ingestion.1.schema.json
templates/include/metadata/ingestionCommonMetadata.1.schema.json
templates/include/metadata/raw.1.schema.json

Per the [Contextual Services Anti-Fraud System plan](https://docs.google.com/document/d/1Db3zxNNeEmJGUtuOYBWwk-DJvBknQDxA0AlfBcYp3RU/edit)
It's unfortunate that this will add a metadata field to all schemas, even though
we only expect this to be set for contextual-services documents.
We could consider folding this value into `x_source_tags` instead within the
Dataflow job to avoid making this schema change at all. We would lose the data
for `payload_bytes_raw` output, though.

Bug 1719353 Add x_foxsec_ip_reputation metadata field

---

schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/glean.1.schema.json
templates/include/glean/url.1.schema.json
validation/glean/glean.1.metrics.pass.json

Bug 1719315 - Add the URL metric type to the Glean schema

---

.circleci/config.yml
Dockerfile

and use `--pull` when building docker image
and use https remote url to avoid ssh host key verification bug (running test locally via `circleci build --job test` stalls on asking for host key verification when using the ssh url)

Use fastestmirror for dnf packages

---

schemas/contextual-services/quicksuggest-click/quicksuggest-click.1.schema.json
schemas/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json
templates/contextual-services/quicksuggest-click/quicksuggest-click.1.schema.json
templates/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json
validation/contextual-services/quicksuggest-click.1.event.pass.json
validation/contextual-services/quicksuggest-impression.1.event.pass.json

This adds a `scenario` field to all the QuickSuggest pings. The pipeline side of change for [bug 1729576](https://bugzilla.mozilla.org/show_bug.cgi?id=1729576).
r? @jklukas

Bug 1729576 - Add scenario to QuickSuggest pings

---

.circleci/config.yml
.github/pull_request_template.md

This repository used to check against a small sample of documents from the pipeline -- this has not been the case for some time. It should be safe to allow CI to run on PRs without manual intervention.

Allow CI to be run on PRs

---

.circleci/config.yml

When PRs get merged into the main branch, CI is run and the bot will post an artifact comparing the contents of the PR to itself. An example: https://github.com/mozilla-services/mozilla-pipeline-schemas/commit/81ad27f4786bd3ba36f0e73fe2aa64de41dbf9cc You can infer the commits being checked by looking at the file names like `bq_schema_81ad27f4-81ad27f4.diff`.
A slightly more useful behavior is to compare against the previous commit when running CI on the main branch. 

Compare integration tests against previous commit on main branch

---

schemas/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json
templates/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json

See https://mozilla-hub.atlassian.net/browse/DENG-45
Note: this should not be merged until https://github.com/mozilla/bigquery-etl/pull/2438 is in place so that we don't interrupt general contextual-services monitoring.

DENG-45 Reduce quicksuggest-impression retention to 2 days

---

schemas/telemetry/crash/crash.4.schema.json
templates/telemetry/crash/crash.4.schema.json

Will resolve [Bug 1745803](https://bugzilla.mozilla.org/show_bug.cgi?id=1745803) "HeadlessMode and BackgroundTaskName being sent in crash pings but not ingested into their own columns in BigQuery".
In addition to the `HeadlessMode` and `BackgroundTaskName` properties mentioned, a `WindowsPackageFamilyName` property is also being added.
---

Bug 1745803 - Add new crash properties to schema

---

README.md

#698 switched from Java 8 to Java 11, but the readme still refers to Java 8.
---

Update readme to reflect Java 11 being used

---

schemas/telemetry/bhr/bhr.4.schema.json
schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/uninstall/uninstall.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json

Fixes bug [1745800](https://bugzilla.mozilla.org/show_bug.cgi?id=1745800). 

Bug 1745800 - Add `environment.system.winPackageFamilyName` to ping table schemas

---

schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/client_info.1.schema.json
validation/glean/glean.1.metrics.pass.json

Bug 1742448 - Add (optional) build date field to client info

---

Dockerfile

fixes #720 
as an alternative to #721, because idk if we actually need centos, and this is more similar to bigquery-etl's Dockerfile

Move docker image from centos 8 to debian bullseye

---

schemas/contextual-services/quicksuggest-click/quicksuggest-click.1.schema.json
schemas/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json
templates/contextual-services/quicksuggest-click/quicksuggest-click.1.schema.json
templates/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json
validation/contextual-services/quicksuggest-click.1.event.pass.json
validation/contextual-services/quicksuggest-impression.1.event.pass.json

Bug 1754622 - Add match_type to QuickSuggest doctypes

---

schemas/messaging-system/cfr/cfr.1.schema.json
schemas/messaging-system/whats-new-panel/whats-new-panel.1.schema.json
schemas/metadata/metaschema/metaschema.1.schema.json
templates/messaging-system/cfr/cfr.1.schema.json
templates/messaging-system/whats-new-panel/whats-new-panel.1.schema.json
templates/metadata/metaschema/metaschema.1.schema.json

In https://github.com/mozilla/gcp-ingestion/pull/2024 I added some code to drop messages when the schema defines a "do not collect after" date.
This updates the schemas for the pings in https://bugzilla.mozilla.org/show_bug.cgi?id=1754044 and sets the `collect_through_date` property to the first of 2022. This will only affect future data in the pipeline so the date is somewhat arbitrary.

Bug 1754044 - Deprecate cfr and whats-new-panel schemas

---

schemas/contextual-services/quicksuggest-block/quicksuggest-block.1.schema.json
templates/contextual-services/quicksuggest-block/quicksuggest-block.1.schema.json
validation/contextual-services/quicksuggest-block.1.event.pass.json

See [Bug 1764669](https://bugzilla.mozilla.org/show_bug.cgi?id=1764669) for the client side patch and data review.
r? @jklukas

Bug 1764669: Add quicksuggest-block to Contextual Services

---

schemas/activity-stream/impression-stats/impression-stats.1.schema.json
schemas/activity-stream/impression-stats/impression-stats.2.schema.json
templates/activity-stream/impression-stats/impression-stats.1.schema.json
templates/activity-stream/impression-stats/impression-stats.2.schema.json
validation/activity-stream/impression-stats.1.sample.pass.json
validation/activity-stream/impression-stats.2.sample.pass.json

Scott Downe and I would like to start tracking on the impression-stats ping. I updated both the v1 and v2 schemas to support the new fields. I did not update any sample events in the /validation subfolder since the new fields are not required.

Bug 1767448 - Add window_inner_height and window_inner_width to impression-stats ping.

---

Dockerfile

Alternative solution to #741, copy build steps from `library/rust:1.63.0-slim-bullseye` to get a newer cargo version.

Update dockerfile to install newer cargo for jsonschema-transpiler

---

schemas/default-browser-agent/default-browser/default-browser.1.schema.json
templates/default-browser-agent/default-browser/default-browser.1.schema.json
validation/default-browser-agent/default-browser.1.sample.pass.json

chore(bug 1765415): added default_pdf_viewer_raw to the schema for default-browser-agent doc

---

schemas/telemetry/bhr/bhr.4.schema.json
schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/uninstall/uninstall.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json

Bug 1797587 - Add environment.system.cpu.name to ping table schemas.

---

schemas/glean/glean/glean.1.schema.json
templates/include/glean/glean.1.schema.json

Glean experiment extras _should_ be `MAP<STRING, STRING>` types. Instead, they are incorrectly typed as a
`STRUCT<type STRING>`.
With this change, we will accomodate the `enrollmentId` field by updating the `extra` field to by:
`STRUCT<type STRING, enrollment_id STRING>`.
This should allow the `enrollmentId`s to propogate, and the experiments should not be included in
`additionalProperties` any longer.

Bug 1751739 - Add enrollment_id to Glean experiments

---

schemas/telemetry/sync/sync.4.schema.json
schemas/telemetry/sync/sync.5.schema.json
templates/include/telemetry/syncItem.1.schema.json

This is a followup to the patch that landed in m-c: [Start tracking reasons individual records failed to sync](https://bugzilla.mozilla.org/show_bug.cgi?id=1820011).
~~- [ ] Update templates/include/glean/CHANGELOG.md~~
For modifications to schemas in restricted namespaces (see [CODEOWNERS](https://github.com/CODEOWNERS)):
~~- [ ] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)~~

Bug 1820011 - Start tracking reasons individual records failed to sync

---

schemas/telemetry/bhr/bhr.4.schema.json
schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/uninstall/uninstall.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json

[Bug 1827233](https://bugzilla.mozilla.org/show_bug.cgi?id=1827233)
adding the `dlsource` column to the tables listed in the bug
There are other tables that have a `dltoken` field and those might also need this `dlsource` column? 
Do I need to trigger something to add those schema changes or will that run automatically? 

add dlsource to schema for telemetry.environment

---

schemas/contextual-services/quicksuggest-block/quicksuggest-block.1.schema.json
schemas/contextual-services/quicksuggest-click/quicksuggest-click.1.schema.json
schemas/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json
templates/contextual-services/quicksuggest-block/quicksuggest-block.1.schema.json
templates/contextual-services/quicksuggest-click/quicksuggest-click.1.schema.json
templates/contextual-services/quicksuggest-impression/quicksuggest-impression.1.schema.json
validation/contextual-services/quicksuggest-block.1.event.pass.json
validation/contextual-services/quicksuggest-click.1.event.pass.json
validation/contextual-services/quicksuggest-impression.1.event.pass.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1839487
https://bugzilla.mozilla.org/show_bug.cgi?id=1779049
adding missing columns "source" for three quicksuggest schemas

Bug 1839487 Missing column for quicksuggest block source

---

schemas/telemetry/bhr/bhr.4.schema.json
schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/uninstall/uninstall.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/bhr.4.sample.pass.json
validation/telemetry/crash.4.sample.pass.json
validation/telemetry/event.4.sample.pass.json

New environment parameter `TargetFrameRate` in `environment.system.gfx`
https://bugzilla.mozilla.org/show_bug.cgi?id=1840381
https://bugzilla.mozilla.org/show_bug.cgi?id=1840398
https://bugzilla.mozilla.org/show_bug.cgi?id=1840395
https://bugzilla.mozilla.org/show_bug.cgi?id=1840378
Also showed up in the new `main_remainder` table where the schema seems to come from some different place, so not sure how to address that.

Bug 1840381 - add  `TargetFrameRate` to `environment.system.gfx`

---

schemas/metadata/metaschema/metaschema.1.schema.json
templates/metadata/metaschema/metaschema.1.schema.json

/CC @Dexterp37 
There's got to be a better natural language description or name for this.
Another option might be to make this e.g. `geoip_index`, with negative values being from the end (the default would be `-3`). The expected value for trusted proxies configuration would be `-4` or `-5` (I can't remember but it's all written down in the Jira ticket).
I'm trying to be explicit about the fact that it's very possible to receive submissions that don't have the expected number of entries when dealing with namespaces that have trusted proxy metadata configured and that there is fallback behavior as a result.

Add geoip skip to metaschema

---

schemas/glean/glean/glean.1.schema.json
templates/include/glean/custom_distribution.1.schema.json
templates/include/glean/memory_distribution.1.schema.json
templates/include/glean/timing_distribution.1.schema.json

This field might be confusing (see https://mozilla.slack.com/archives/C4D5ZA91B/p1693101626243669) and should not be used at analysis.

Bug 1799509 - Add description to Glean `_distribution` metrics' count field

---

schemas/metadata/metaschema/metaschema.1.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
templates/metadata/metaschema/metaschema.1.schema.json
templates/telemetry/first-shutdown/first-shutdown.4.schema.json
templates/telemetry/main/main.4.schema.json
templates/telemetry/saved-session/saved-session.4.schema.json

requires https://github.com/mozilla/mozilla-schema-generator/pull/250
fixes [bug 1851057](https://bugzilla.mozilla.org/show_bug.cgi?id=1851057)
context: I missed some histograms when splitting out use counter pings, and now they need to be moved, but their schema needs to be preserved in the remainder pings because schemas are not allowed to delete fields.

Move histograms related to use counters to the correct subset pings

---

schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
templates/telemetry/first-shutdown/first-shutdown.4.schema.json
templates/telemetry/main/main.4.schema.json
templates/telemetry/saved-session/saved-session.4.schema.json

[Bug 1852630](https://bugzilla.mozilla.org/show_bug.cgi?id=1852630)
requires https://github.com/mozilla/mozilla-schema-generator/pull/252 and blocks https://github.com/mozilla/bigquery-etl/pull/4276

Bug 1852630 - Rename main_remainder_v4 to main_v5

---

schemas/firefox-installer/install/install.1.schema.json
templates/firefox-installer/install/install.1.schema.json

Added new schema fields for distribution ID and version to installer ping schema.

Bug 1665381 - Added distribution fields to stub installer ping schema

---

schemas/glean/glean/glean.1.schema.json
scripts/inject-metadata
templates/glean/defaults.schema.json
templates/include/glean/glean.1.schema.json

Alternate to https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/805 that allows omission of default metadata while still propagating any explicitly set `mozPipelineMetadata`.

Remove glean1 bq table metadata alternate

---

schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/client_info.1.schema.json
validation/glean/glean.1.metrics.pass.json

Bug 1862955 - add (optional) session_id & session_count to Glean client info

---

schemas/telemetry/bhr/bhr.4.schema.json
schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/sync/sync.4.schema.json
schemas/telemetry/sync/sync.5.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/uninstall/uninstall.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json
templates/include/telemetry/syncPayload.1.schema.json

This is a follow-up to https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/799 to address https://bugzilla.mozilla.org/show_bug.cgi?id=1875874 and https://bugzilla.mozilla.org/show_bug.cgi?id=1877339.
Related incident doc: https://docs.google.com/document/d/1M7ageyDdS8sha0vYTbWwJrsRylrJgUYArjogCpHeL2Q/edit
This change allows distro and distroVersion to be present and null instead of either not present or present and non-null.

Bug 1875874 - Allow null distro and distroVersion in legacy telemetry

---

schemas/telemetry/bhr/bhr.4.schema.json
schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/uninstall/uninstall.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json

Unfortunately, when attempting to run the build scripts to run the tests, I got this error:
```
=> CACHED [stage-0  2/15] RUN set -eux;     apt-get update;     apt-get install -y --no-install-recommends         ca-certificates         gcc         libc6-dev         wget         ;     dpkgArch="$(dpkg --print-architecture)";     case "${dpkgArch##*-  0.0s
=> CACHED [stage-0  3/15] RUN mkdir -p /usr/share/man/man1 &&     apt-get update -qqy &&     apt-get install -qqy         cmake         diffutils         gcc         g++         jq         make         wget         git         openjdk-11-jdk-headless     0.0s
=> CACHED [stage-0  4/15] RUN cargo install jsonschema-transpiler --version 1.9.0 …
```

Bug 1892312 - Add `recoveredFromBackup` to environment schema.

---

schemas/glean/glean/glean-min.1.schema.json
schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/metrics.1.schema.json

bug 1657947 - New Glean metric types labeled_{custom|memory|timing}_distribution

---

Dockerfile

Recent releases of setuptools cause the build to fail. This fixes it and will unblock https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/822

Pin setuptools version to 70.3.0

---

schemas/telemetry/bhr/bhr.4.schema.json
schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/uninstall/uninstall.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/main.4.sample.pass.json

Bug 1907663 - Add scale factor fields to gfx

---

schemas/telemetry/bhr/bhr.4.schema.json
schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/uninstall/uninstall.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json
validation/telemetry/event.4.sample.pass.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1910462
This was added to firefox two years ago but never added to the schema and didn't have significant volume until now https://searchfox.org/mozilla-central/source/toolkit/components/telemetry/docs/data/environment.rst#88
Verified the path with
```sql
SELECT
additional_properties
FROM
`moz-fx-data-shared-prod.telemetry_stable.event_v4`
WHERE
DATE(submission_timestamp) = '2024-07-29'
AND additional_properties LIKE '%"msstoresignedin"%'
AND sample_id = 5
```

Bug 1910462 - Add msstoresignedin to legacy telemetry environment

---

schemas/glean/glean/glean-min.1.schema.json
schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/labeled_group.1.schema.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1929078
This should fix the increase we are seeing in `org.everit.json.schema.ValidationException: #/metrics/labeled_boolean/browser.ui.mirror_for_toolbar_widgets/<some long label>: expected maxLength: 61, actual: <some number bigger than 61>`

[Bug 1929078] Increase maxLength for labeled groups to 71

---

schemas/glean/glean/glean-min.1.schema.json
schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/metrics.1.schema.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1932210
Goes with https://github.com/mozilla/mozilla-schema-generator/pull/281

Bug 1932210 - Add labeled_quantity glean metric type

---

schemas/telemetry/crash/crash.4.schema.json
templates/telemetry/crash/crash.4.schema.json

https://bugzilla.mozilla.org/show_bug.cgi?id=1952961
Add missing field `payload`.`metadata`.`NimbusEnrollments`

[Bug 1952961] Add NimbusEnrollments to crash schema

---

schemas/telemetry/bhr/bhr.4.schema.json
schemas/telemetry/crash/crash.4.schema.json
schemas/telemetry/dnssec-study-v1/dnssec-study-v1.4.schema.json
schemas/telemetry/event/event.4.schema.json
schemas/telemetry/first-shutdown/first-shutdown.4.schema.json
schemas/telemetry/heartbeat/heartbeat.4.schema.json
schemas/telemetry/main/main.4.schema.json
schemas/telemetry/modules/modules.4.schema.json
schemas/telemetry/new-profile/new-profile.4.schema.json
schemas/telemetry/saved-session/saved-session.4.schema.json
schemas/telemetry/shield-icq-v1/shield-icq-v1.4.schema.json
schemas/telemetry/testpilot/testpilot.4.schema.json
schemas/telemetry/third-party-modules/third-party-modules.4.schema.json
schemas/telemetry/uninstall/uninstall.4.schema.json
schemas/telemetry/untrusted-modules/untrusted-modules.4.schema.json
schemas/telemetry/update/update.4.schema.json
schemas/telemetry/voice/voice.4.schema.json
templates/include/telemetry/environment.1.schema.json

Related to https://bugzilla.mozilla.org/show_bug.cgi?id=1926292
`ecount`, `pcount`, `mcount` got never added to the schemas and is showing up as missing column. I'm not sure if the description is accurate here since it also wasn't added to the docs in `environment.rst`. Maybe @Bas-moz or @chutten, can you check if the description makes sense?
https://bugzilla.mozilla.org/show_bug.cgi?id=1928441

[Bug 1928441] Add pcount, mcount, ecount to cpu environment

---

schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/client_info.1.schema.json

- [in progress] If coming from a fork, run integration tests: `./.github/push-to-trigger-integration <username>:<branchname>`
- [n/a] Follow the [change control procedure](https://docs.google.com/document/d/1TTJi4ht7NuzX6BPG_KTr6omaZg70cEpxe9xlpfnHj9k/edit#heading=h.ttegrcfy18ck)

bug 1955428 - Add client_info.attribution and client_info.distribution

---

schemas/glean/glean/glean.1.schema.json
templates/include/glean/client_info.1.schema.json

Follow up to https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/841
Missing `type`s caused [schema generator to fail today](https://workflow.telemetry.mozilla.org/dags/probe_scraper/grid?search=probe_scraper&dag_run_id=scheduled__2025-03-31T00%3A00%3A00%2B00%3A00&task_id=mozilla_schema_generator&tab=logs) with:
```
[2025-04-01, 04:58:21 UTC] {pod_manager.py:496} INFO - [base] Exception: Missing type for schema element at key client_info/attribution
```

Bug 1955428 - Add missing type property to client_info.attribution and client_info.distribution

---

schemas/glean/glean/glean-min.1.schema.json
schemas/glean/glean/glean.1.schema.json
templates/include/glean/CHANGELOG.md
templates/include/glean/labeled_group.1.schema.json

See https://bugzilla.mozilla.org/show_bug.cgi?id=1965335 and https://bugzilla.mozilla.org/show_bug.cgi?id=1965337
The allowed label length is 111 after it got upped in https://bugzilla.mozilla.org/show_bug.cgi?id=1959696

Set allowed Glean label maxLength to 111

---

CMakeLists.txt
README.md

Cmake 4.0.0 removed compatibility for versions <[3.5](https://github.com/Kitware/CMake/releases/tag/v3.5.0): https://cmake.org/cmake/help/latest/release/4.0.html#deprecated-and-removed-features.  I updated recently so build fails for me.  Setting to 3.18 which is the version in the debian docker image.

Set cmake minimum to 3.18
